### ISSUE TITLE
Create node status: 'consensus', 'catchup' and 'booting'

### ISSUE THREAD

**Issue by spikeekips** [bosnet/sebak#11]
Node will get it's status:
* `consensus`: node is currently participating consensus process
* `catchup` : node is catch up the blocks
* `booting`: node is preparing to be consensus
* `terminating`: node is going to shutdown(#9)

**Comment by kfangw** [comment]
Is it ongoing?

**Comment by Charleslee522** [comment]
Are the names of the status confirmed in #9?

**Comment by astonshnam** [comment]
If I finish #124, I am going to start this.
