### ISSUE TITLE
API: Response format application/hal+json

### ISSUE THREAD

**Issue by kfangw** [bosnet/sebak#118]
http://stateless.co/hal_specification.html

**Comment by Geod24** [comment]
That makes sense if we provide a RESTful API. Is that the intent ?

**Comment by kfangw** [comment]
yeap. I intend to build a RESTful APIs.
But, after build a response as it is, I will change the response later.

**Comment by outsideris** [comment]
What is better than just plain JSON.
It seems similar to HATEOAS.

**Comment by spikeekips** [comment]
RFC is https://tools.ietf.org/html/rfc4627 .

**Comment by spikeekips** [comment]
Good job @kfangw
