### ISSUE TITLE
API: Paging support

### ISSUE THREAD

**Issue by kfangw** [bosnet/sebak#122]
If there is a lots of data to be sent to client, it may be a burden to network.

We need an idea to support paging for regular API call and streaming call both.

**Comment by Geod24** [comment]
Something like https://developer.github.com/v3/guides/traversing-with-pagination/ ?

**Comment by kfangw** [comment]
yes, but i am not sure for streaming.
I will attach details when I am clear for this issue.

**Comment by kfangw** [comment]
#118 the resource is expressed in the JSON+HAL

**Comment by kfangw** [comment]
cursor, ordering is needed

**Comment by anarcher** [comment]
How to represent the `cursor` in HTTP Request/Response? 
- GET querystring  such like`?cursor={cursor}&limit={limit}` 
-  cursor =  `{key_prefix}-{index_item}-{block_height}-{sequence_id}-{uuid}` ?  We can need some kind of `paging_token`?

**Comment by anarcher** [comment]
What do you think about it? 

```
type Paging struct {
     Cursor  string `json:cursor`
     Limit uint64 `json:limit`
     Order string `json:order`
  
     err error // maybe?
}

//r := *http.Request 
p := NewPaging(r) // validate inputs
if p.Error() != nil { // or p.Validate() error 
     // return error
}

bks := GetBlockByXXX(p.Cursor,p.Limit,p.Order)
```

**Comment by anarcher** [comment]
I think this issue is closed :-) I will close it!!!
