### ISSUE TITLE
Proposal: use sequence id instead of checkpoint

### ISSUE THREAD

**Issue by outsideris** [bosnet/sebak#123]
We should prove a concept of sequence that is enough to replace current checkpoint.

Below is summary
-------

Checkpoint consists of `Subtracted-Added` form. Now, we understand the concept of the checkpoint.

## Advantage
- We can check the balance fo the account because TX has a previous hash, which is a checkpoint.

## Limitations
- Only one TX by one account is processed at the same time. A user can make new TX after previous TX consented and a new block is updated checkpoint.
    - We can include multiple TXs in one TX as operations. However, it is a kind of workaround. We don't say it now because it is not related to this issue.
- Only one TX by one account is processed at the same time, but we can process TXs by other accounts. So, each node saves block different order in DB. The order is different, but the blocks should be same. So, it is like a tree or blockchains by account.
    - I know there are many arguments about this. However, it is another big subject. We don't say this here.
    - Please open an issue if you want

## Conclusion
According to Mathias (@Geod24) the above is wrong.

The checkpoint is only for what balance we will use for validation.
- Sent time
- Consensus time

# Misc
> We can check the balance fo the account

The checkpoint is only for validation, not consensus, not block.
We trust transaction by signing, and we already know what is the latest hash for the account.

> Only one TX by one account is processed at a same time.

I think it is a good imitation. However, checkpoint doesn't guarantee only one TX. It is `waiting box` and `voting box`. If account send two TX with the current checkpoint, we cannot validate them

**Comment by Geod24** [comment]
So after much discussion it turns out that:
- Checkpoint was modeled after Stellar's sequence ID (which also uses an account model)
- The intent was to check the user have enough fund at the moment the transaction is issued
- This led to #60 , and thus we do not check the added part anymore because we cannot rely on it
- As a result, the added part does not provide any value as data in the blockchain
- Since we do not check added, we cannot fulfill the original intent
- Checkpoint's only utility is to prevent replay attack
- The is what Stellar's sequence ID are for
- Sequence ID are more lightweight and totally ordered

**Comment by Charleslee522** [comment]
Several action items appeared as follows:
- In the sequence number model, make sure about how to validate the transaction.
- Fix the payment policy - Credit card vs Debit card(=check card)
- Let's show it in code @outsideris @Geod24 @zzim2x @Charles
- Split milestone for publishing @spikeekips

**Comment by spikeekips** [comment]
Like #140 , there are already PR for this proposal, so I think this proposal can be proceeded in new branch for fast development.

**Comment by Geod24** [comment]
Given the concept of checkpoints is so spread in the code, going for another branch would lead to tons of conflicts, and that's not something I am very keen on. What would it take to get it accepted in master instead ?

**Comment by spikeekips** [comment]
@Geod24 Please share the complete concept of seq id to replace the current checkpoint. I suggest to use branch because I think the idea for seq id is still in development.

**Comment by Geod24** [comment]
Done in #140
