### ISSUE TITLE
Refactor the package hierarchy

### ISSUE THREAD

**Issue by Geod24** [bosnet/sebak#129]
As brought up by @anarcher during our last meeting, the package hierarchy is currently quite flat and hard to make sense of.
One quick to spot offender is `block`. We have `block.go`, `block_operation.go`, `block_transaction.go`, etc... It would make much more sense if they were placed into a `block` subfolder.
This applies to a few other areas, like `node_runner`.
I plan to submit a PR to provide a deeper hierarchy. Any opposition ?

**Comment by kfangw** [comment]
it is solved by https://github.com/bosnet/sebak/pull/352
Could you close the issue if there are no more things to discuss? @Geod24

**Comment by Geod24** [comment]
Yep, thanks @kfangw !
