### ISSUE TITLE
CLI Wallet: Create Account

### ISSUE THREAD

**Issue by spikeekips** [bosnet/sebak#133]
(related to #1 )
To make new payment, `create-account` will be done before it.

**Comment by Geod24** [comment]
Should an account have an initial balance ?

**Comment by spikeekips** [comment]
@Geod24 Yes, the current minimum initial balance for new account is `0.1` BOS(`1000000`) in BOScoin tokennet.

**Comment by outsideris** [comment]
Resolved by #93
