### ISSUE TITLE
Support HTTP

### ISSUE THREAD

**Issue by outsideris** [bosnet/sebak#155]
Currently, sebak supports only HTTPS.
Because of that, a node must have cert files, and it is hard to handle for operating multiple nodes.
If sebak supports both HTTP and HTTPS, SREs can register certificates on load balancers and operate sebak node with HTTP. If so, SREs can automate updating certificates easily.

**Comment by Geod24** [comment]
I would add that, given the nature of a blockchain, HTTPS is superfluous:
- No private data is exchanged
- The data is public
- The certificates are not used for any auth

**Comment by spikeekips** [comment]
@outsideris 👍 
> @Geod24 : I would add that, given the nature of a blockchain, HTTPS is superfluous:

I think I see the classic debate over HTTP vs HTTPS. Many people argued that HTTPS was only necessary for password-protected website, but I remember debate is over at this time. As we know, all the data of public blockchain is public in it's nature and no private data can be shared. But it true when we look at the data itself. We also should consider the communication between clients and blockchain network, and even inside blockchain network. If we provide HTTPS by default, **basically** we can prevent any 3rd party from tempering or recoding data. Data is public, that does not mean transferring data is also public.
