### ISSUE TITLE
Go Test fail: TestHTTP2NetworkGetNodeInfo

### ISSUE THREAD

**Issue by scottmatheina** [bosnet/sebak#156]
?   	github.com/bosnet/sebak/cmd/sebak	[no test files]
?   	github.com/bosnet/sebak/cmd/sebak/cmd	[no test files]
?   	github.com/bosnet/sebak/cmd/sebak/cmd/key	[no test files]
?   	github.com/bosnet/sebak/cmd/sebak/cmd/wallet	[no test files]
?   	github.com/bosnet/sebak/cmd/sebak/common	[no test files]
ok  	github.com/bosnet/sebak/lib	152.809s
ok  	github.com/bosnet/sebak/lib/common	0.503s
?   	github.com/bosnet/sebak/lib/common/test	[no test files]
?   	github.com/bosnet/sebak/lib/error	[no test files]
--- FAIL: TestHTTP2NetworkGetNodeInfo (0.00s)
	http2_network_test.go:146: Get https://localhost:51064/node/: dial tcp 127.0.0.1:51064: getsockopt: connection refused
127.0.0.1 - - [29/Jun/2018:18:30:51 +0000] "GET /node/ HTTP/2.0" 200 15 "" "v-n1"
127.0.0.1 - - [29/Jun/2018:18:30:51 +0000] "POST /node/connect HTTP/2.0" 200 15 "" "v-n1"
127.0.0.1 - - [29/Jun/2018:18:30:51 +0000] "GET /node/ HTTP/2.0" 200 143 "" "v-n1"
127.0.0.1 - - [29/Jun/2018:18:30:51 +0000] "POST /node/connect HTTP/2.0" 200 143 "" "v-n1"
127.0.0.1 - - [29/Jun/2018:18:30:51 +0000] "GET /node/ HTTP/2.0" 200 143 "" "v-n1"
127.0.0.1 - - [29/Jun/2018:18:30:51 +0000] "POST /node/message HTTP/2.0" 200 91 "" "v-n1"
127.0.0.1 - - [29/Jun/2018:18:30:52 +0000] "GET /node/ HTTP/2.0" 200 143 "" "v-n1"
127.0.0.1 - - [29/Jun/2018:18:30:52 +0000] "POST /node/ballot HTTP/2.0" 200 91 "" "v-n1"
FAIL
FAIL	github.com/bosnet/sebak/lib/network	9.252s
?   	github.com/bosnet/sebak/lib/observer	[no test files]
ok  	github.com/bosnet/sebak/lib/storage	1.120s

------------- Below are my custom install instructions for digital ocean ubuntu 16.04 LTS VPS ----
note: these instructions worked a couple weeks ago with no issue when i created my own private network. 

# install sebak on digital ocean ubuntu 16.04 LTS VPS server

# create your digital ocean server

# create your SSH key pair, and add to your github.com profile

$ ssh-keygen -t rsa

# copy public key to github profile

$ cat ~/.ssh/id_rsa.pub

# Install Go 1.9 or greater

$ apt-get update

$ wget https://storage.googleapis.com/golang/go1.9.2.linux-amd64.tar.gz

$ tar -zxvf  go1.9.2.linux-amd64.tar.gz -C /usr/local/

# create your working directory, and GOBIN directory
$ mkdir $HOME/work
$ mkdir $HOME/work/bin

# set the PATH variables, I've chosen to make these permanent variables in
# ~/.profile NOTE: you have to paste these into the file

$ sudo vi ~/.profile

# select i to edit text

# copy the below 2 lines into the file

export GOPATH=/root/work
export PATH=$PATH:/usr/local/go/bin:$GOPATH/bin

# press ESC when done, then :x to exit

# this will print the contents of the file so make sure it saved correctly

$ cat ~/.profile

# the next command will reset the .profile, so your system can see the GOPATH

$ source ~/.profile

# check the go version, it should be go1.9.2

$ go version 

# you can check the go environment with 'go env' but not required

# install "dep" https://github.com/golang/dep#installation

$ curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh

# inside the "work" folder we created, create a folder titled "sebak"

$ mkdir $HOME/work/sebak

$ cd $HOME/work/sebak

# I had an issue with using 'go get' and had to set git config variables because
# we are working with a private repository, but this command fixes that issue.
# this may be an extra step since the repository is now public.  

$ git config --global url."git@github.com:".insteadOf "https://github.com/"

$ go get github.com/bosnet/sebak

$ cd $HOME/work/src/github.com/bosnet/sebak

# when you installed 'dep', and if you installed correctly, and your GOPATH 
# variables are configured correctly, then 'dep ensure' will run without any issues. 
# if there is a problem, there will be an error message - fix it.
# the 'dep ensure' command will take a while to process.  

$ dep ensure

$ go install github.com/bosnet/sebak/cmd/sebak

# Install the OpenSSL cert following these instructions 
# I prefer letsencypt to generate a valid TLS certificate

$ cd ~
$ sudo apt-get update
$ sudo apt-get install software-properties-common
$ sudo add-apt-repository ppa:certbot/certbot
$ sudo apt-get update
$ sudo apt-get install certbot 

$ sudo certbot certonly --standalone -d mydomain.com

# you will need to look at the letsencypt message for the location of your
# certificate and keys

# to update

$ cd ~/work/src/github.com/bosnet/sebak
$ git pull

# Test
# you must be in the ~/work/src/github.com/bosnet/sebak directory

$ cd ~/work/src/github.com/bosnet/sebak
$ go test ./...

**Comment by Geod24** [comment]
@scottmatheina : You might want to replace `github.com/bosnet/sebak` with `boscoin.io/sebak` everywhere. Your approach should work but can have unforeseen consequences.

**Comment by scottmatheina** [comment]
Well it’s all a work in progress and i did my instructions weeks ago while in korea before testnet launch. I’ll give it a shot. I was told by jinhwanchoi to change github.com to boscoin.io so I’ll do that. thanks

Scott

**Comment by outsideris** [comment]
@scottmatheina  Can we close this?

**Comment by scottmatheina** [comment]
Yes. I will reinstall and try again. 

Scott
