### ISSUE TITLE
Finished ballot will store the reason in 'BlockTransactionError'

### ISSUE THREAD

**Issue by spikeekips** [bosnet/sebak#17]
If the ballot is finished and failed to get consensus, the reason must be stored in `BlockTransactionError`

**Comment by Charleslee522** [comment]
@spikeekips Is this related with #23 ?
I mean, the expired ballot in reserved box is the finished and failed one, right?

**Comment by spikeekips** [comment]
> @Charleslee522  Is this related with #23 ? I mean, the expired ballot in reserved box is the finished and failed one, right?

This issue describes that the failed finished transaction must be stored in `BlockTransactionError` with  the failed reason. The client can check whether the transaction it sent is successfully finished or not.

Yes, the expired ballots in reserved box also must be stored in `BlockTransactionError`.

**Comment by Geod24** [comment]
I would need some clarification on this:
- If the ballot is finished => This only applies to valid transactions, right ? The ones that pass all checks, including signature, account balance, etc...
- Does `BlockTransactionError` need to be shared with any other node ? Can one query it ?
- How often do we prune `BlockTransactionError`'s storage ?
- Do we use this data for anything ?

**Comment by spikeekips** [comment]
related to #404, this issue will be closed.

**Comment by Geod24** [comment]
It's not the same though. #404 is about how we respond to the request, this is about what we store in the blockchain (AFAIU)
