### ISSUE TITLE
Getting started page issue

### ISSUE THREAD

**Issue by booeunsoeng** [bosnet/sebak#173]
In getting started "sebak commands" page,  errors are occur when i try "sebak genesis" and "sebak node"  commands.

In this page, just write 
`sebak genesis GDUGDDCHYCVOSHG6LI62OP7VQVBW65PMPKKLYL272RBO6QIYDTQTR6HN` 

but when i tried this, this error is occur.
`boo@ubuntu:~/sebak/src/boscoin.io/sebak$ sebak genesis GDUGDDCHYCVOSHG6LI62OP7VQVBW65PMPKKLYL272RBO6QIYDTQTR6HN
error: invalid '--network-id'; --network-id must be given
`

i think this test command needs to be changed to include 'network-id'  for beginner. 

Also, In https://github.com/bosnet/sebak/wiki/Deploy-SEBAK-Network-At-First-Time,

The 'Running' test command is like this:

> sebak node \
>     --network-id "this-is-test-sebak-network" \
>     --endpoint "https://localhost:12345" \
>     --tls-key "sebak.key" \
>     --tls-cert "sebak.crt" \
>     --storage "file:///tmp/db-n0" \
>     --secret-seed SCN4NSV5SVHIZWUDJFT4Z5FFVHO3TFRTOIBQLHMNPAZJ37K5A2YFSCBM \
>     --validator "https://localhost:12346?address=GDPQ2LBYP3RL3O675H2N5IEYM6PRJNUA5QFMKXIHGTKEB5KS5T3KHFA2 https://localhost:12347?address=GCZG7MBKRSS6MJVZOALYBJB5C223FSZ43MDTPX2O4UGQTCXTHWBDNUB6" \
>     --log-level debug \ 

This error is occur:  Error: unknown flag: --validator

I think  '--validator' is need to be changed  to '--validators'

**Comment by spikeekips** [comment]
Thanks @booeunsoeng, [Deply Network](https://github.com/bosnet/sebak/wiki/Deploy-SEBAK-Network-At-First-Time) page was updated.
