### ISSUE TITLE
Catchup process

### ISSUE THREAD

**Issue by spikeekips** [bosnet/sebak#18]
When new validator join a network, it will have no blocks, so the newbie should catch up all the blocks from other validators.

**Comment by Charleslee522** [comment]
Is there any order by transaction? If not, how could it be caught up partially? by @outsideris

**Comment by spikeekips** [comment]
@Charleslee522 @outsideris We need more discussion on catchup process. We can find the order of transaction by checkpoint.

**Comment by outsideris** [comment]
As we understanding, there is no order of transactions across accounts. Right?

**Comment by spikeekips** [comment]
@outsideris Across accounts? Hmm. Starting from genesis account, the new transaction from one account to the other can be chained and traceable, so I think we can order the transactions.

**Comment by outsideris** [comment]
hmm... 

1. only one transaction of an account is processed at the same time
2. But, other transactions of other account is processed concurrently.

Right?  For Example

1. `A1` account sent `tx1` to `A2` account
1. `B1` account sent `tx2` to `B2` account
1. `tx1` and `tx2` sent same time
1. nodes make consensus both `tx1` and `tx2` at same time
1. so, one node can have `tx1` - `tx2` order and another node can have `tx2` - `tx1`.

I think this scenario is possible.

**Comment by spikeekips** [comment]
@outsideris As we discussed today, the validation of tx is done between only source and target, not checking by global something. In your case, the order of `tx1` and `tx2` will not be important in current impl.

**Comment by outsideris** [comment]
But, it's important to catchup process.

**Comment by spikeekips** [comment]
@outsideris Yeah, it will be easy to impl catchup if we can order the entire transaction.

**Comment by Geod24** [comment]
> @outsideris As we discussed today, the validation of tx is done between only source and target, not checking by global something. In your case, the order of tx1 and tx2 will not be important in current impl.

Looks like I missed this. Could you expand on this point ?

**Comment by spikeekips** [comment]
This was moved to https://github.com/bosnet/sebak/milestone/2 .

**Comment by Charleslee522** [comment]
Now, we have block and new issues #297, #298, #301, #302.
