### ISSUE TITLE
Support 'HTTP-Problem' in API response

### ISSUE THREAD

**Issue by spikeekips** [bosnet/sebak#19]
The detailed specification of 'HTTP-Problem' can be found in https://tools.ietf.org/rfc/rfc7807.txt .

**Comment by Geod24** [comment]
Given that:
- the APIs are still being developed
- this has little impact on the core of our product
- the ROI is pretty low

I moved this to the `MainNet` milestone

**Comment by spikeekips** [comment]
Good job @kfangw
