### ISSUE TITLE
Proposer selection function

### ISSUE THREAD

**Issue by Charleslee522** [bosnet/sebak#202]
Every nodes in network must select the proposer by itself using the function below.

IsaacRound.go:CalculateProposer()

Input
- Connected node addresses
- Block Height
- Round

Output
- Proposer node address

**Comment by cmcm2222** [comment]
why don't you PR for New proposer ? 
If do, it would be so helpful understand this issue. I guess.

**Comment by sconeman** [comment]
https://github.com/spikeekips/sebak/blob/d0e6cb4d79fbf9c25addacc7057f274dab6fa59a/lib/node_runner_round.go#L412
@spikeekips @Charleslee522 Is not `CalculateProposer()` already developed?

**Comment by Charleslee522** [comment]
@sconeman Oh, I guess so :) @spikeekips Already did it 👍

**Comment by Charleslee522** [comment]
@sconeman You could add unittest codes for `CalculateProposer()` :)

**Comment by sconeman** [comment]
@Charleslee522 OK I will.

**Comment by sconeman** [comment]
I added test cases in `lib/node_runner_test.go`.
