### ISSUE TITLE
Transaction validation for the new ISAAC

### ISSUE THREAD

**Issue by Charleslee522** [bosnet/sebak#203]
Validating every transactions in proposed block is needed.
It should validates,
- balance of source
- sequenceID
- base fee
- verify signature
- transaction hash
- etc...

**Comment by Charleslee522** [comment]
@spikeekips which features do you want to check for tx validation?

**Comment by spikeekips** [comment]
@Charleslee522 The things you pointed is done by `Transaction.IsWellformed()`, so I try to add like these,

* check there are same source in the proposed transactions
* check source and target accounts exist
* check the total amount of transaction is valid
* etc.

**Comment by Charleslee522** [comment]
@spikeekips I want you to explain more about "check there are same source in the proposed transactions" please :)

**Comment by spikeekips** [comment]
@Charleslee522 If there are 2 or more transactions from same source account in the proposed transactions, the first one will be considered as valid, the left will not be included in `ValidTransactions`.

**Comment by Charleslee522** [comment]
@spikeekips Why the second tx from the same source is invalid? If balance is enough and tx has no dependency with the first one, then isn't it ok.

**Comment by Geod24** [comment]
> If balance is enough and the second tx has no dependency with the first one, then isn't it ok?

It's one or the other, but you cannot have both.
If we use sequence ids, they either have the same sequence ID (= replay) or one has sequence id `S` and the other `S + 1`.

**Comment by spikeekips** [comment]
@Charleslee522 👍
