### ISSUE TITLE
Changing checkpoint to sequenceID to defend replay attack

### ISSUE THREAD

**Issue by Charleslee522** [bosnet/sebak#204]
The transaction has the Checkpoint to defend replay attack. But it could be changed to sequenceID of sender. Then, it would be efficient and simple.

```
Checkpoint string -> SequenceID uint64
```

**Comment by Charleslee522** [comment]
#203

**Comment by kfangw** [comment]
how is going? @Geod24

**Comment by spikeekips** [comment]
This issue can be closed, right?

**Comment by Geod24** [comment]
Right!
