### ISSUE TITLE
Transaction sharing without INIT voting

### ISSUE THREAD

**Issue by Charleslee522** [bosnet/sebak#205]
The old version of ISAAC shared the transaction by transferring the INIT ballot voting of the existing ISAAC.
It was not good for performance and resource. So we need a better solution for transferring transactions.

**Comment by sconeman** [comment]
@spikeekips A ballot state called `TXSHARE` was created. Is this right before `INIT`?

**Comment by Charleslee522** [comment]
@spikeekips @sconeman I already removed this state, but it has revived...
I'm going to check it again :)

**Comment by sconeman** [comment]
@Charleslee522 Aha... So I will remove again.

**Comment by Charleslee522** [comment]
@sconeman That's ok. I can handle it :)
