### ISSUE TITLE
The limitation of the number of transactions in one proposed block

### ISSUE THREAD

**Issue by Charleslee522** [bosnet/sebak#209]
In the current version of the new ISAAC, there is no limitation of the number of transactions in one block.
The whole transactions which is gathered in 2 seconds(It can be changed) will be included into the block. So, I guess, the limitation is needed.

**Comment by Charleslee522** [comment]
@cmcm2222 Exactly. From now, we have transaction pool and propose block with whole txs in the pool. To resolve this issue, picking top n txs in transaction pool is needed. I guess txs needs to be ordered by received time.

**Comment by Charleslee522** [comment]
It had been implemented in https://github.com/bosnet/sebak/pull/215/files#diff-e33f7f460f666841210e11844c21d6abR21

**Comment by spikeekips** [comment]
With this [`MaxTransactionsInBallot`](https://github.com/spikeekips/sebak/blob/new-proposer/lib/node_runner.go#L28), we need to check the number of transactions in the proposed ballot is over it.
