### ISSUE TITLE
Expired 'VotingResult' in 'VotingBox' must be moved to 'ReservedBox'

### ISSUE THREAD

**Issue by spikeekips** [bosnet/sebak#21]
If `VotingResult` is stayed too long(almost over 2 minutes) in `VotingBox`, it should be moved to `ReservedBox`

**Comment by leejames00** [comment]
Why are the `Message.Hash`es sorted in `BallotBox`? Will it be replaced by a `combining function`?

https://github.com/bosnet/sebak/blob/3cf6918f8c17ad4f8215c459ad00c2a4420ebb92/lib/ballot.go#L380

**Comment by Charleslee522** [comment]
@leejames00 Would you please let me know in detail about `combining function`?

**Comment by leejames00** [comment]
I was confused on why the `Message.Hash`es need to be sorted. 
Because in SCP, the transaction sets are merged (by a combining function) into one message(or hash)... so if a combining function is implemented, there would be no need for sorting

**Comment by Charleslee522** [comment]
Aha, there is no `combining function` in sebak yet. All transactions are handled as they are.

**Comment by leejames00** [comment]
and also I was thinking about timeouts to `VotingResult` -- if the `VotingResult` should be moved from `VotingBox` to `ReservedBox` after 2minutes, I think the message hash should be mapped with time

for example,
```
type BallotBox struct {
	sebakcommon.SafeLock

	Hashes map[sort.StringSlice]time.Time
}
```

or if there are other suggestions on implementing timeouts please comment :)

**Comment by Charleslee522** [comment]
If time is recorded, you have to check how long does it take periodically.
I figure, using [time.ticker](https://gobyexample.com/tickers) is better.

**Comment by astonshnam** [comment]
I don't think I need to record time. After the message is moved to the `ReservedBox`, we don't have to check the time data in the message.

**Comment by leejames00** [comment]
@astonshnam but after 2 minutes in `VotingBox`, it should be moved to `ReservedBox. How do you check that the `VotingResult` is expired?

**Comment by astonshnam** [comment]
@leejames00 However, a time check is only needed within the `VotingBox`. It is unnecessary to change the structure of the `BallotBox` because of the process in the `VotingBox`. I want to think about other ways.

**Comment by leejames00** [comment]
Aha I agree. I was thinking about other ways too

**Comment by astonshnam** [comment]
What do you think about changing `BallotBox` to interface type?

**Comment by astonshnam** [comment]
`Node` is also an interface type. As follows..
```
type Node interface {
	Address() string
	Keypair() *keypair.Full
	SetKeypair(*keypair.Full)
	Alias() string
	SetAlias(string)
	Endpoint() *Endpoint
	Equal(Node) bool
	DeepEqual(Node) bool
	GetValidators() map[string]*Validator
	AddValidators(validators ...*Validator) error
	HasValidators(string) bool
	RemoveValidators(validators ...*Validator) error
	Serialize() ([]byte, error)
}
```

**Comment by Charleslee522** [comment]
I figure, we need the independent struct `BoxManager` or `ResultManager`
This struct can handle `Results` and `Boxes` validation, move hashes each other, etc...
We can discuss about it tomorrow in detail :)

**Comment by Charleslee522** [comment]
I have an idea. I figure, if ticker is attached every ballot, then it is not that good for performance. So, It is better to check every 2 minute by saving snapshot. @astonshnam @leejames00

**Comment by leejames00** [comment]
So do you mean checking the `VotingBox`, `WaitingBox`, and `ReservedBox` every 2 minutes? I think it's a good idea since the the `VotingResult` does not have to expire in "exactly" 2 minutes. A drawback could be a `votingResult` waiting for 3min59s before expiring to next box

**Comment by Charleslee522** [comment]
1. save current state(snapshot) and check validity(uniqueness of hash in boxes)
1. after 2 min, compare to previous snapshot and find target to move the other box
1. Repeat above

In the worst case, some ballot may take 4 min to move `WaitingBox` to `ReservedBox`. But this is not that big a deal.

**Comment by Charleslee522** [comment]
@leejames00 You fully understand my word :)

**Comment by anarcher** [comment]
Maybe I don't understand this issue, Is it(gist) right? 
gist: https://gist.github.com/anarcher/b8e895f9793b87c1012f101f1bea6af7

**Comment by Charleslee522** [comment]
@anarcher @astonshnam 
I figure it is better to talk about this issue ASAP. Cause we did duplicated works :)

fyi @spikeekips
