### ISSUE TITLE
Modify the new ISAAC to match status of all nodes similarly

### ISSUE THREAD

**Issue by Charleslee522** [bosnet/sebak#210]
All nodes propose and stack blocks at regular intervals. If there is no features to synchronize, the nodes in the network will have different timings when enough time goes through.
So we need some features to synchronize timing of nodes in the network.

**Comment by cmcm2222** [comment]
What about bring NTP server like as Stellar?

**Comment by Charleslee522** [comment]
@cmcm2222 Sorry, I changed "time" to "timing" in summary. As we said, "time" issue will be handled in system level.

**Comment by Charleslee522** [comment]
When the network is running for a long time, the state of all nodes should be at most equal.
Surely, nodes status could be matched from catch-up process, but being frequently catch-up condition is no good to network performance.
Therefore, to match status of all nodes similarly, I want to add features into the design as follow,
1. When the node receive `INIT` ballot, if it is invalid, it broadcasts ballot with `No` voting to keep going instead of restarting from `Propose`.
1. When the node current state is `SIGN` or `ACCEPT` and time is over, it broadcasts ballot with `Nil` voting to keep going instead of restarting from `Propose`.

**Comment by Geod24** [comment]
> state of all nodes should be at most equal

I assume you meant to say "mostly equal", as in equal most of the time. Almost equal wouldn't be a good thing ;)

> being frequently catch-up condition is no good to network performance.

We don't have evidence of that.

> A node saves the ballot which has later state than itself.

If a node receives a ballot that is "too high" for it, I don't see how it can vote about it anyway ?

**Comment by Charleslee522** [comment]
@Geod24 
> I assume you meant to say "mostly equal", as in equal most of the time. Almost equal wouldn't be a good thing ;)
Thanks

> We don't have evidence of that.
Yes but we can predict easily. For example, when the node get into catch-up, then it needs to check voting state, height and receive new block, and sync ...
So I think the node should be in catch-up as little as possible.

> If a node receives a ballot that is "too high" for it, I don't see how it can vote about it anyway ?
I cannot understand what "too high" means :)

**Comment by Charleslee522** [comment]
@Geod24 
> If the node gets into catch-up, it means something went wrong. Loss of connectivity, for example. If the node goes into catch-up when everything works as expected - it would be a serious design issue.

Exactly.
I mean, for example, let's assume that
1. a node loses Ballot(Height:1, `SIGN`) from all nodes because of network issue.
1. After then the node can receive Ballot(Height:1, `ACCEPT`) from all nodes.
In this state, the node can decide to keep going because it has higher ballot or stop and catch-up because there are no `SIGN` ballot.
In this case, I want to take former because it is reasonable.

> That means higher than it's current status. So if the node knows of the block at height 42, it'll expect a ballot on block 43. But if it gets a ballot on block 44, it cannot vote until it knows of 43.

Good point. I thought that ballots on block 44 will stored only ballot pool. After confirmed block 43, ballots can be used.

**Comment by Charleslee522** [comment]
This issue is only for design and documentation. The implementation will go with the new specific issues.

**Comment by Charleslee522** [comment]
Saving future state ballot issue is split into #250
