### ISSUE TITLE
Some performance experiments

### ISSUE THREAD

**Issue by Charleslee522** [bosnet/sebak#214]
I did an experience with 
https://github.com/spikeekips/sebak/blob/new-proposer/lib/common/util_benchmark_test.go
The goal is,
1. to find out which is faster, `string slice` or `string map` when finding a string.
2. to determine which is faster, `string slice` or `string map` or `string map with hashing` when checking equality.

> $ go test ./lib/common/ -bench=.
```
goos: darwin
goarch: amd64
pkg: boscoin.io/sebak/lib/common
BenchmarkFoundInStringSlice500-8      	 2000000	       955 ns/op
BenchmarkFoundInStringMap500-8        	20000000	        72.2 ns/op
BenchmarkFoundInStringSlice1000-8     	 1000000	      1791 ns/op
BenchmarkFoundInStringMap1000-8       	20000000	        76.6 ns/op
BenchmarkFoundInStringSlice5000-8     	  200000	      9196 ns/op
BenchmarkFoundInStringMap5000-8       	20000000	        87.8 ns/op
BenchmarkEqualityOrderedSlice500-8    	 1000000	      1372 ns/op
BenchmarkEqualityMap500-8             	  100000	     14249 ns/op
BenchmarkEqualityMapWithHash500-8     	 1000000	      1747 ns/op
BenchmarkEqualityOrderedSlice1000-8   	  500000	      2723 ns/op
BenchmarkEqualityMap1000-8            	   50000	     29616 ns/op
BenchmarkEqualityMapWithHash1000-8    	 1000000	      1751 ns/op
BenchmarkEqualityOrderedSlice5000-8   	  100000	     14079 ns/op
BenchmarkEqualityMap5000-8            	   10000	    157504 ns/op
BenchmarkEqualityMapWithHash5000-8    	 1000000	      1764 ns/op
```

Result
> 1. to find out which is faster, `string slice` or `string map` when finding a string.

The string map is faster than string slice. As big o notation, string map is O(log n) and string slice is O(n). So I changed string slice to string map in https://github.com/spikeekips/sebak/blob/new-proposer/lib/ballot.go#L143

> 2. to determine which is faster, `string slice` or `string map` or `string map with hashing` when checking equality.

The `string map with hashing` is the fastest. As big o notation, `string map with hashing` is O(1) but, `string slice` and `string map` are O(n).

**Comment by Charleslee522** [comment]
@spikeekips Please check when you review my commits.

**Comment by Charleslee522** [comment]
I'm going to change the file util_benchmark_test.go link after merging this source.

**Comment by sconeman** [comment]
It is a good approach.
