### ISSUE TITLE
How to handle Transaction Fee?

### ISSUE THREAD

**Issue by spikeekips** [bosnet/sebak#257]
There are several issues we should consider about 'Transaction Fee'.

* Where are the collected fees stored? Is it necessary?
* How to calculate the collected Transaction Fee for distributing them?
* etc.

**Comment by kfangw** [comment]
Is it needed to be solved until the opening bosnet?

**Comment by spikeekips** [comment]
@kfangw I will handle this issue, especially the first one,  "Where are the collected fees stored?" with #63 .

**Comment by spikeekips** [comment]
The transaction fee will go to the common budget account.

**Comment by spikeekips** [comment]
#83
