### ISSUE TITLE
Graceful Stop

### ISSUE THREAD

**Issue by spikeekips** [bosnet/sebak#26]
Useful library: https://github.com/facebookgo/grace

**Comment by spikeekips** [comment]
@anarcher At first, the reason for 'graceful restart' was that the node needed to be restarted to update new version or new validator list, or anything else to be applied new environments.

**Comment by anarcher** [comment]
> I'm wondering that too. I don't see much value in implementing graceful restart in app. Graceful stop is a nice feature though.
@Geod24 I agree with your opinion! :-) 

> @anarcher At first, the reason for 'graceful restart' was that the node needed to be restarted to update new version or new validator list, or anything else to be applied new environments.

IHMO, 'graceful restart' **without dropping any connections** (facebookgo/grace) is not suitable for node. 

For changing validator list, we should stop and start a node with the new validator arguments.
At some time, If old node process and new node process tries to access same leveldb, one of them get a failure to connect. 

I feel safe to stop and start a node but, with graceful stop :-)
So, I would like to change this issues title 'Graceful Stop' :-)

**Comment by spikeekips** [comment]
@anarcher It will be unnecessary for receiving message from client, because it does not need to keep connection, and the other cases like 'event-stream' can be ignored. As you suggested, 'graceful stop' will be good.
