### ISSUE TITLE
Write API document

### ISSUE THREAD

**Issue by outsideris** [bosnet/sebak#274]
For client development, public API document is needed as Swagger or Postman format.

It is best if we make API document automatically from source.

**Comment by anarcher** [comment]
- https://github.com/growler/go-slate

**Comment by anarcher** [comment]
We can close it? @kfangw @outsideris  Maybe we can fill more information of it. But I would like to care with another new issue and PR.. :->

**Comment by anarcher** [comment]
- Add github page :  https://bosnet.github.io/sebak/api/index.html
- Thanks! @outsideris !!

**Comment by anarcher** [comment]
I will close it now, If we have another issues or needs, we will make other issues for it. :->
