### ISSUE TITLE
Refactoring API structure

### ISSUE THREAD

**Issue by kfangw** [bosnet/sebak#286]
Several weeks ago, @anarcher @zzim2x mentioned restructuring API in person.

Description will be filled soon.

**Comment by kfangw** [comment]
Could you share your code snippet here? @zzim2x

**Comment by anarcher** [comment]
Ping @zzim2x

**Comment by zzim2x** [comment]
I've not found the code. It might seem to be on my other laptop.

**Comment by spikeekips** [comment]
Can we close this issue?

**Comment by anarcher** [comment]
Yes, I will close it.   :-)
