### ISSUE TITLE
List up Client API

### ISSUE THREAD

**Issue by kfangw** [bosnet/sebak#287]
Current implementation contains Account/Transaction API
There might be more API which the wallet client need
List up the APIs and Specs

**Comment by anarcher** [comment]
# Node API

- `/node/blocks/lastest/`
- `/node/blocks/hash/:hash`
- `/node/blocks/height/:height`
- `/node/transactions/pool/`
- `/node/transactions/`
- `/node/transactions/db/`

# Client API

- `/api/transactions/:hash`
- `/api/block/:hash`
- `/api/block/height/:height`

@outsideris @kfangw  We need a time to discuss the api naming? :->

**Comment by kfangw** [comment]
I am reading this stellar API document
https://www.stellar.org/developers/horizon/reference/endpoints/accounts-single.html
We may find missing API by looking the document

**Comment by kfangw** [comment]
# Client API

* Account
/accounts
/accounts/:id
/accounts/:id/transactions
/accounts/:id/operations

* Transaction
/transactions
/transactions (POST)
/transactions/:id

* Block
/blocks
/blocks/:id
/blocks/:id/transactions
/blocks/:id/operations

* Operation
/operations
/operations/:id

**Comment by outsideris** [comment]
We should add APIs for frozen accounts.

**Comment by kfangw** [comment]
@Geod24 @soonkuk @cmcm2222 @kyehyukahn Please note the APIs what you need

**Comment by kfangw** [comment]
@spikeekips Can we list up APIs what the exchanges used?

**Comment by spikeekips** [comment]
> @kfangw :  Can we list up APIs what the exchanges used?

There were some questions to see the all operations of a given account. Stellar Horizon has `effects` for account, 
https://www.stellar.org/developers/horizon/reference/endpoints/effects-for-account.html .

**Comment by spikeekips** [comment]
After this issue ends up, we can wrap the details about APIs to the wiki page.

**Comment by anarcher** [comment]
@kfangw I think this PR can be closed. what do you think?

**Comment by kfangw** [comment]
@anarcher agreed
