### ISSUE TITLE
Modifying package name(`sebakcommon` -> `common`, ...)

### ISSUE THREAD

**Issue by Charleslee522** [bosnet/sebak#289]
There are some reasons for modifying.
1. All package names start with same prefix `sebak`. I think it means nothing.
1. Package name `sebakcommon` is too long

Related #288 
PS.
> How about make another pkg such as ballot or voting pkg?
And using common instead of sebakcommon (It is a naming issue)
If we need to import same pkg names , IMHO, We change a name of outside pkg instead of our pkg name. ( import std_log "log" , import btc_common "btc/common"). :->

**Comment by anarcher** [comment]
- https://blog.golang.org/package-names

**Comment by spikeekips** [comment]
@Charleslee522 I suggest, 

* `sebakcommon` -> `common`
* `sebaknetwork` -> `network`
* `sebakstorage` -> `storage`
* `sebakerror` -> `sebakerror`
* `block` -> `block` 👍 
* `sebaknode` -> `node`
* `observer` -> `observer`

To make pkg name to be shorter will be good, and further our pkg name should be general and if some conflict with another outside pkgs, we can use import alias. But `sebakerror` is a pain in the ass. `error` is the built in type and `errors` is also well-known pkg. :(

**Comment by anarcher** [comment]
As already you know, std errors pkg has one func, so we can use import alias or  type alias if we need to it. 

For example, upspin project uses just errors pkg name: https://github.com/upspin/upspin/blob/master/errors/errors.go
