### ISSUE TITLE
Ricardian Contract format.

### ISSUE THREAD

**Issue by soonkuk** [bosnet/sebak#294]
The ricardian contract is used to describe the condition and action of PF.
It will be signed and recorded in the blockchain by the publisher.
When PF voting procedure is executed, each voting transaction must refer to the ricardian contract
and signed voting transaction will be the evidence that voter has agreed on the contents of the ricardian contract.
It will need to first define the ricardian contract format.

**Comment by kfangw** [comment]
@soonkuk How is going?

**Comment by kfangw** [comment]
@soonkuk PING

**Comment by spikeekips** [comment]
@soonkuk Ping, me too~

**Comment by soonkuk** [comment]
I don't make it yet.
I will finish in this week.

**Comment by kfangw** [comment]
@soonkuk congrats for the first commit 👍

**Comment by soonkuk** [comment]
> @soonkuk congrats for the first commit 👍

@kfangw Thanks~! :)

**Comment by soonkuk** [comment]
We will change the format of ricardian contract from markdown to yaml.
