### ISSUE TITLE
For entering `SYNC` state, a node checks the block height from ACCEPT ballots.

### ISSUE THREAD

**Issue by Charleslee522** [bosnet/sebak#297]
https://github.com/bosnet/sebak/wiki/How-to-SYNC-blocks-with-validators

There are four node states in ISAAC.
1. NodeStateBOOTING
1. NodeStateSYNC
1. NodeStateCONSENSUS
1. NodeStateTERMINATING

After booting, NodeState is `SYNC` first. Then a node checks that whether it can be part of consensus or not.
For doing that, a node receives ACCEPT ballots.
When these exceed the threshold, node finds the block heights in ballot and transit a node state to `SYNC` or `CONSENSUS`.

**Comment by kfangw** [comment]
I want to watch this issue
