### ISSUE TITLE
Implement frozen accounts

### ISSUE THREAD

**Issue by Geod24** [bosnet/sebak#307]
We should implement frozen accounts.
In short a frozen account is just like a normal account, except:

- It cannot receive new transaction after it has been created
- It can only be created with amount which are multiple of 10k BOS
- It has a link to the reward account (the public address)
- One can only withdraw the integrality of the account balance

My suggestion is to add a `--freeze` option to `sebak wallet pay`.

**Comment by soonkuk** [comment]
I think it also should have a below exception.
- The Sender of create transaction should be equal to reward account.

**Comment by Geod24** [comment]
That depends on how we do the reward system. But at first look, I'm not sure that's necessary (although it'll be the default in the CLI).

**Comment by kyehyukahn** [comment]
Does the frozen account need a new public address system, such as a different prefix value?

**Comment by Geod24** [comment]
I think so.
