### ISSUE TITLE
Versioning 'Transaction', 'Ballot', etc.

### ISSUE THREAD

**Issue by spikeekips** [bosnet/sebak#31]
The incoming messages like `Transaction`, `Ballot`, etc already have `Version` field, at this time in development we just leave it blank. We need the version management and versioning itself.

* How to manage version of messages
* How to make version(string)

**Comment by spikeekips** [comment]
> @leejames00 : https://github.com/bosnet/sebak/blob/d01dfb9f1f939ad5f1da19cdce8d413985031880/lib/ballot.go#L49
> What is T? Is it `Title`?

https://github.com/bosnet/sebak/blob/d01dfb9f1f939ad5f1da19cdce8d413985031880/lib/ballot.go#L187-L188

It means type of `Message` https://github.com/bosnet/sebak/blob/d01dfb9f1f939ad5f1da19cdce8d413985031880/lib/common/message.go#L3
As you expected, `Ballot.T` always "ballot".

**Comment by spikeekips** [comment]
#32

**Comment by anarcher** [comment]
Since  #689 is merged, this PR will be closed. :->
