### ISSUE TITLE
Congress Voting: Messages and API

### ISSUE THREAD

**Issue by soonkuk** [bosnet/sebak#311]
Proposal about congress voting and voting result should be stored in the blockchain.
We should implement the transaction operation type about proposal and voting result and define operation data.

**Comment by kfangw** [comment]
May I take this Issue? @soonkuk

**Comment by kfangw** [comment]
https://blockchainos.atlassian.net/wiki/spaces/BOS/pages/556302380/Congress+Voting+Messages+and+API
