### ISSUE TITLE
package split(package sebak => package sebak, block, account, transaction)

### ISSUE THREAD

**Issue by Charleslee522** [bosnet/sebak#344]
There are too many `Structs` in sebak package. So I and @anarcher rearranged packages and directories.
We also wanted to move test files like `lib/ballot_test.go` to `lib/ballot`, but it is more complex so I'm going to make new issue for it.

### package account
 lib/{block => account}/account.go
 lib/{block => account}/account_test.go
 lib/{block => account}/test.go

### package ballot
lib/{ => ballot}/ballot.go
lib/{common => ballot}/ballot_state.go
lib/{common => ballot}/voting.go

### package block
 lib/{ => block}/block_header.go
 lib/{ => block}/block.go

### package transaction
 lib/{ => transaction}/block_operation.go
 lib/{ => transaction}/block_transaction.go
 lib/{ => transaction}/block_transaction_history.go
 lib/{ => transaction}/operation.go
 lib/{ => transaction}/operation_create_account.go
 lib/{ => transaction}/operation_payment.go
 lib/{ => transaction}/transaction.go
 lib/{ => transaction}/transaction_checker.go
 lib/{ => transaction}/transaction_pool.go

### package common
 lib/{ => common}/constant.go

**Comment by spikeekips** [comment]
Ping #352 are doing similar job.

**Comment by kfangw** [comment]
Some idea, like ballot, can be done on the branch.

**Comment by Charleslee522** [comment]
Resolved in #352
