### ISSUE TITLE
'Checkpoint' must not be made formerly, client can not guess the checkpoint of it’s transaction

### ISSUE THREAD

**Issue by spikeekips** [bosnet/sebak#35]

**Comment by Geod24** [comment]
Can you provide more details ? Or is this a duplicate of https://github.com/bosnet/sebak/issues/60 ?

**Comment by Geod24** [comment]
I assume it was. Also, we have #123 now.

**Comment by spikeekips** [comment]
#123 is just proposal at this time. This issue still is valid for this code.

**Comment by Geod24** [comment]
So can you provide more details on what you mean by "not made formally" ?

**Comment by spikeekips** [comment]
@Geod24 I mean, before sending transaction, client must get the latest checkpoint of it's account. Under the current checkpoint mechanism, the next checkpoint can be calculated.
