### ISSUE TITLE
Dashboard and transaction browser

### ISSUE THREAD

**Issue by spikeekips** [bosnet/sebak#37]
* Transaction flow
* Network status
* Trace transaction, operation and account

**Comment by Geod24** [comment]
What would it look like ? A web interface ?

**Comment by outsideris** [comment]
If so(web), this should be included in this repo?

**Comment by spikeekips** [comment]
If we will miss this issue, this can be removed from this repo.

**Comment by outsideris** [comment]
This is related a kind of status page which we said about?

**Comment by Geod24** [comment]
> If so(web), this should be included in this repo?

Yeah that was my underlying question too. If it does, it really qualifies as a separate project.

**Comment by Geod24** [comment]
We have https://github.com/bosnet/tokennet-explorer and adaptation to sebak should be done there, so closing this

**Comment by spikeekips** [comment]
@Geod24 Tokennet-explorer is for tokennet, not sebak, but this issue was for
Remind.

**Comment by Geod24** [comment]
@spikeekips : I was under the impression we would adapt `tokennet-explorer` to sebak. Or should we rewrite something from scratch ?

**Comment by spikeekips** [comment]
@Geod24 Hmm, if possible I wish, but it will not be easy I guess  :)
