### ISSUE TITLE
Implementation sending transaction fee according to operation type.

### ISSUE THREAD

**Issue by soonkuk** [bosnet/sebak#381]
## Background
The transaction fee is sent to the specific account in general.
But for some specific transaction which has operations like as voting result, membership, issuance the transaction fee may be exempted.

## Solution
Include sending tx fee in FinishOperation function of each operation type basically.
According to operation type some FinishOperation functions can omit sending tx fee.

**Comment by spikeekips** [comment]
Please update subject, 'Transaction fee' is too ambiguous.
