### ISSUE TITLE
API: Cache Responses

### ISSUE THREAD

**Issue by anarcher** [bosnet/sebak#390]

**Comment by spikeekips** [comment]
I can fill the missing description of this issue :)

* Most of API relies on storage, we need to reduce the usage of storage

This is checklist.

- [ ] `BlockXX` records should be cached; except `BlockAccount`
- [ ] Caching `BlockAccount` records and it's expiration can be `1s` for considering very frequent requests
- [ ] `404` also should be cached, but it's expiration can be `1s` or `2s`
- [ ] Cache server can be embedded as memory type
- [ ] Cache should support external cache server like 'memcached', 'redis', or 'AWS elastic cache', etc.

**Comment by kfangw** [comment]
IMO, Redis would be satisfying the requirements.
On the Redis, It is very easy to use and set the TTL.

**Comment by spikeekips** [comment]
@kfangw Yes, redis will be good. There are some libraries for various kind of the existing cache system, https://github.com/avelino/awesome-go .

**Comment by anarcher** [comment]
Using redis means deploy is going to hard. 
Hashicorp lru cache is not bad option IMHO

**Comment by anarcher** [comment]
- https://github.com/coocood/freecache
- https://github.com/karlseguin/ccache
- https://github.com/allegro/bigcache

**Comment by anarcher** [comment]
IMHO, LRU+ observer based eviction is better than time-based

**Comment by spikeekips** [comment]
@anarcher: The cache responses are handled by URL-based? If it is, how about CacheMiddleware? 

It will be good, if we can manage different cache policy by handler, as I described BlockAccount should be managed differrently.

**Comment by anarcher** [comment]
It's just prototyping. 

```
cacheMiddleware := cache.NewMiddleware(
   cache.Option{
       Adapter: "mem",
       AdapterOption: "max=1000,expire=2s",
       MatchURLPrefix : "/v1/api/account", 
   },
   cache.Option{
       Adapter: "redis",
       AdapterOption: "endpoint=127.0.0.1:11211,max=1000",
       MatchURLPrefix : "/", 
   }
}

```

**Comment by anarcher** [comment]
```
cached := cache.New(
            cache.WithExpire(1 *time.Second),
            cache.WithAdpater("mem",10000),
            cache.WithStatusCode(200,1 *  time.Second),
            cache.WithStatusCode(404,1 * time.Minute),
)
nr.network.AddHandler(
          apiHandler.HandlerURLPattern(api.GetTransactionOperationsHandlerPattern),
          cached.Handler(apiHandler.GetOperationsByTxHashHandler),
      ).Methods("GET", "OPTIONS")
```

**Comment by Geod24** [comment]
@anarcher :
- What's the unit of 10000 (line 2) ?
- Expire at 1s is very low, isn't it ?
- What are the two status codes for ?

Other than that, it looks pretty expressive 👍

**Comment by anarcher** [comment]
-  What's the unit of 10000 (line 2) ?
  Yes, max item limit. 

- Expire at 1s is very low, isn't it ?
  It's an example or sample.  and reference it 
>  Caching BlockAccount records and it's expiration can be 1s for considering very frequent requests


- What are the two status codes for ?
Reference it :
 > 404 also should be cached, but it's expiration can be 1s or 2s

**Comment by Geod24** [comment]
> IMHO, LRU+ observer based eviction is better performance than time-based

I agree with this, and I think it's also more correct.
This this, I expect that the expiration can be fairly high (hours).

**Comment by anarcher** [comment]
> I agree with this, and I think it's also more correct.
This this, I expect that the expiration can be fairly high (hours).

I would like to do time expire based.

**Comment by Geod24** [comment]
> I would like to do time expire based.

What changed your mind ? Also, what is the strategy to avoid serving stale data ?

**Comment by anarcher** [comment]
>  Caching BlockAccount records and it's expiration can be 1s for considering very frequent requests
