### ISSUE TITLE
Drop Go v1.10 support and use v1.11 only

### ISSUE THREAD

**Issue by Geod24** [bosnet/sebak#395]
Go v1.11 introduced support for go modules.
Since we use a lot of modules, dropping support for Go v1.10 would greatly simplify our CI / update process, as we can get rid of `dep` completely and use only the Go tool.

**Comment by kfangw** [comment]
r u sure that 1.11 working well without bug?
I am worried that it might have faults because 1.11 is introduced only a few weeks ago.

**Comment by anarcher** [comment]
With go1.11 , gomodule is still experimental. :-> (https://blog.golang.org/go1.11)

**Comment by Geod24** [comment]
> Although the details of module support may change, projects that convert to modules using Go 1.11 will continue to work with Go 1.12 and later.

[Source](https://golang.org/doc/go1.11#modules)
I don't say we have to do it right now, but we should consider doing it sooner than later.

**Comment by outsideris** [comment]
Otherwise, we need a rule when we will drop v1.10.

**Comment by anarcher** [comment]
I am OK to use go mod instead of dep. But about picking default/running (in production) go version , we should do conservative.
Personally I would like to choose which version of big project such as docker or k8s choose in their stable version. :-) 
But maybe go1.11 seems look good to run production:-)

**Comment by Geod24** [comment]
Docker seems to be [pretty eager to upgrade](https://github.com/docker/docker-ce/commit/38974ef6a25315017aa9fd79fa78420d7a422fb0).
I couldn't find anything conclusive in k8s.

**Comment by Geod24** [comment]
Fixed in #478 (See also #485 )
