### ISSUE TITLE
API: Transaction history -to event stream-

### ISSUE THREAD

**Issue by spikeekips** [bosnet/sebak#4]
(almost same with #3)

This api can be used to check how the transmitted transaction(from client) is finished,
* tx gets consensus successfully?
* or tx is failed because of some reason
---
* If tx gets consensus successfully, the response will have `BlockTransaction` data.
* If failed, the response will have `BlockTransactionHistory` data.

**Comment by kfangw** [comment]
If a client get `BlockTransaction` or `BlockTransactionHistory`, there is no more data to be sent to the client i think.
Then, the server should drop the connection right?
@spikeekips

**Comment by spikeekips** [comment]
> @kfangw : If a client get `BlockTransaction` or `BlockTransactionHistory`, there is no more data to be sent to the client i think. Then, the server should drop the connection right? @spikeekips 

If not in 'event-stream', connection should be stopped by server-side, but in 'event-stream', the server and client should stay put in connection and wait for newly added transactions, is it make sense?
