### ISSUE TITLE
Support to set public endpoint in `sebak node run --publish`

### ISSUE THREAD

**Issue by spikeekips** [bosnet/sebak#400]
Currently `sebak node run` support to set network binding with `--endpoint` option. If node are running in internal subnet and it has different network endpoint for outside of the subnet.
```
-- subnet: 192.168.0.xxxx
node0(192.168.0.1) node1(192.168.0.2)

-- outside subnet: 49.171.139.xxx
node2(49.171.139.165)
```
`node0` can connect to `node2, but `node2` can not to `node0`.

The requirements are,
* rename the current `--endpoint` to `--bind`
  - if the `host` part is `localhost`, network will be bind to `localhost`
  - if the `host` part is not `localhost`, network will be bind globally
* create new option, `--publish`
  - this will be used for other nodes and clients
    - `--validators` of other nodes
    - node info
    - HAL resource response
  - If does not set `--publish` option, the `--bind` will be used instead

**Comment by Geod24** [comment]
👍 for `bind`

Is it `--publish` or `--public` ? The title use the later but the description uses the former.
I'm not sure I understand what `--publi{sh,c}` is for ?

**Comment by spikeekips** [comment]
@Geod24 —publish, I mean it.
