### ISSUE TITLE
API: Block

### ISSUE THREAD

**Issue by kfangw** [bosnet/sebak#407]
Client API for Blocks.
It may be required by exchanges and explorer.

/blocks
/blocks/:hash
/blocks/:hash/transactions
/blocks/:hash/operations

**Comment by spikeekips** [comment]
Is it related to the #301 ?

**Comment by kfangw** [comment]
Implementation of the handler may be similar to the #301 
But the request/response may differ.
This API called by clients, not nodes.

Implementation of this API may be pend until the #301 is done.
I defer to your decision.

@spikeekips

**Comment by kfangw** [comment]
I will work on this as soon as #712 merged.
@zzim2x @outsideris I heard that you guys need this feature.

**Comment by anarcher** [comment]
IHMO, If we just have two endpoints , I think it is enough. 

- `/blocks`
- `/blocks/:hashOrHeight` 

What do you think? :->
