### ISSUE TITLE
API: Fill document with details and review it

### ISSUE THREAD

**Issue by kfangw** [bosnet/sebak#409]
I am not sure the document can be verbose for each field.
first of all, follow the existing documentation system, and discovery improvement point and fill it.

reference.
https://apiblueprint.org/documentation/tutorial.html
https://github.com/danielgtaylor/aglio

**Comment by anarcher** [comment]
For generating APi HTML doc (https://bosnet.github.io/sebak/api), I will do it until CI automation. :-)

**Comment by kfangw** [comment]
@cmcm2222 Could you try this out?

cd {where your sebak location}
`npx aglio -i ./docs/API.md -o ./docs/xxx.html`
And open the xxx.html on any browser.

**Comment by cmcm2222** [comment]
@kfangw I got it.
