### ISSUE TITLE
Confirmed field of BlockTransaction

### ISSUE THREAD

**Issue by kfangw** [bosnet/sebak#438]
https://github.com/bosnet/sebak/blob/bb40f328b530ce2787989ba8962afcd2df7dfc38/lib/block/transaction.go#L110-L125

IMO, Stored data for BlockXXX should be the same for every node. It is a blockchain data
But according to the current implementation, the confirmed field is different.

Should this need to be the same?

Furthermore, when the ```sync``` activated, the value of the confirmed field differs greatly

**Comment by kfangw** [comment]
@anarcher @Charleslee522 @spikeekips what do you think about this?

**Comment by kfangw** [comment]
btw, Is the field necessary?

**Comment by spikeekips** [comment]
@kfangw For information, `Block` generated by proposer's `Ballot`(`NewBlockFromBallot`), so `Block.Confirmed` value is from `Balot.ProposerConfirmed()`.

**Comment by kfangw** [comment]
@spikeekips The code snippet comes from `BlockTransaction`

**Comment by spikeekips** [comment]
@kfangw `BlockTransaction.Confirmed` should be set from `Block.Confirmed`, right?

**Comment by kfangw** [comment]
@spikeekips yeap. I think so.
But I am worried that I missed a reason for AS-IS implementation.

**Comment by spikeekips** [comment]
@kfangw The current impl should be bug :) I convince YOU RIGHT 👍

**Comment by kfangw** [comment]
OK. thanks for your explanation.
I will upload relevant PR soon. @spikeekips

**Comment by kfangw** [comment]
> btw, Is the field necessary?

Ah... one more question remains
I want your opinion.

**Comment by spikeekips** [comment]
@kfangw After you issued, now I don't know it should be necessary :)

**Comment by Charleslee522** [comment]
@spikeekips @kfangw 
`block.Confirmed` field is necessary in https://github.com/bosnet/sebak/pull/426
It is used when calculating the blockTimeBuffer.
But only the Confirmed of latest block is used. So it no needs to save in database or blockchain.

**Comment by spikeekips** [comment]
@kfangw pointed BlockTransaction.Confirmed

**Comment by Charleslee522** [comment]
Okay. I figure, it could be removed :)

**Comment by kfangw** [comment]
fixed by #454
