### ISSUE TITLE
Hash for BlockOperation

### ISSUE THREAD

**Issue by kfangw** [bosnet/sebak#439]
https://github.com/bosnet/sebak/blob/ae5a58e519743cde45ea0cf4efcb972f3ff27347/lib/block/operation.go#L37-L55

Actually, Hash of BlockOperation is not ```Hash``` 
It is combined string by a hash of operation and a hash of the transaction
`return fmt.Sprintf("%s-%s", op.MakeHashString(), tx.GetHash())`
Currently, Operation Hash is used as a database key.

Like `Block` consist of hashes of the transactions,
`BlockTransaction` should consist of hashes of the operations

According to the current implementation, 
hashing transaction needs whole operation data but stored operations in the `BlockTransaction` is the hash of operation.
It means that the `BlockTransaction` is not self-provable.

**Comment by kfangw** [comment]
How about adding the sequence number to `operation` to prevent hash collision?
If then, we can make the unique hash for every operation.

**Comment by kfangw** [comment]
@anarcher @spikeekips @Geod24 I want to listen to your opinion

**Comment by spikeekips** [comment]
@kfangw As I mentioned, `Transaction.Hash` looks like redundant, but it can be possible to check signature without calculating `Hash` in node-side.

**Comment by kfangw** [comment]
@spikeekips It is the totally different issue what we discussed in person.

**Comment by spikeekips** [comment]
@kfangw At this time, we can simply verify the BlockTransaction with original message, that is, checking Hash is matched, but it's not what we want.

**Comment by kfangw** [comment]
fixed by #445
