### ISSUE TITLE
PF issuance

### ISSUE THREAD

**Issue by soonkuk** [bosnet/sebak#459]
Generate coin issuance for PF budget

**Comment by soonkuk** [comment]
Generate coin issuance for PF

**Comment by soonkuk** [comment]
#308

**Comment by soonkuk** [comment]
PF issuance is a kind of inflation.
This inflation is a special transaction only congress voting account can do and this transaction pays no fee.
To do this, SEBAK knew the congress voting account from starting.
The congress voting account makes transactions for saving proposal, voting result and generate issuance.
The congress voting account use valid secret key and public address to sign transaction but real account is not need to be created because the congress voting account does not send coin and does not pay fee.

Issuance operation data

name | type | description
:----|:--------|:-------
voting | string | tx hash of voting result(congress voting result)
amount | uint64 | inflation amount
target | string | target address

**Comment by kfangw** [comment]
I take this.

**Comment by kfangw** [comment]
solved by #719
