### ISSUE TITLE
Provide a way to accept the list of validator via environment variables

### ISSUE THREAD

**Issue by Geod24** [bosnet/sebak#46]
Currently all arguments can be provided via environment variable, with the notable exception of `--validator`.
Fixing that would simplify the docker process a bit.

**Comment by Geod24** [comment]
Did this get fixed ?

**Comment by spikeekips** [comment]
@Geod24 Your previous #47 can handles `SEBAK_VALIDATORS`, right?

**Comment by Geod24** [comment]
Well not from Sebak itself, which is what this issue is about.

**Comment by spikeekips** [comment]
Ah~ sorry, I missed.

**Comment by Geod24** [comment]
Done in #135
