### ISSUE TITLE
API: Operations by account to event stream

### ISSUE THREAD

**Issue by spikeekips** [bosnet/sebak#5]
(almost same with #3 )

This api will produce the all the operations of each account. The account address can be set in path. The response will have 'BlockOperation' data.

**Comment by kfangw** [comment]
There can be two alternatives.
1. send whole `BlockOperation`s to client. And If there is an event, send whole `BlockOperation`s again with newly updated `BlockOperation`
2. send whole and after that, send only newly updated `BlockOperation` in the stream

For the second strategy, I am not sure about this situation.
- What happens, update an item when iterate keys from leveldb with iterator function?
iterator working on a snapshot?

@spikeekips

**Comment by spikeekips** [comment]
@kfangw I think you already have answer :)
