### ISSUE TITLE
Client API : get a list of frozen accounts

### ISSUE THREAD

**Issue by zzim2x** [bosnet/sebak#507]
We need to be able to get a list of ‘create-account’ operations that are still frozen.

**Comment by soonkuk** [comment]
I will make api like this /v1/accounts/{address}/frozenAccounts.
It take input as general account address and output related froze account addresses.

It work like this.
when node save frozen account, 
make key with prefix(BlockAccountFrozenCreatedPrefix) + linked address of frozen account + getuniqueIDfromUUID() and use this key for saving address of frozen account.

Then later node can find the frozen account address related to general account(lined address).

@spikeekips @kfangw How about this?

**Comment by kfangw** [comment]
As I told you in person, It is possible.
But there should be a rationale for supporting this features in SEBAK.
IMO, this requirement may be met by client-side.

@spikeekips may help you to decide it.

**Comment by spikeekips** [comment]
As we know, client can not find the frozen accounts from general account at this time, (but can find general account from the frozen accounts :) ) This feature is necessary for client to find the frozen accounts from general account. 

I want to suggest the new url path, `/api/v1/accounts/{address}/frozen-accounts` :)

**Comment by soonkuk** [comment]
@kfangw @spikeekips Then I will make PR for this issue.

**Comment by kfangw** [comment]
When you implement this issue, please write an integration test for it at `tests/client`

@soonkuk

**Comment by soonkuk** [comment]
> When you implement this issue, please write an integration test for it at `tests/client`
> 
> @soonkuk

OK I will do it.

**Comment by zzim2x** [comment]
IMO, `prefix + general account address + block height + sequence id + UUID`

I think I need some fields.

* `source address` : general account address
* `target address` : frozen account address
* When a create-account operation was accepted, `sequence id`, `block height` and `initial amount`.
* `state` : ex) frozen, melting, unfrozen, returned. 
* When an unfreeze request was accepted, `unfreeze request op hash` and `block height`.
* `payment request op hash`

Why we need them:

* validating voting results
* validating freezing rewards
* Finding a list of frozen accounts of a general account specified
