### ISSUE TITLE
Support node profiling

### ISSUE THREAD

**Issue by anarcher** [bosnet/sebak#508]
For  CPU & Memory profiling, Prepare sebak profiling enabled. 
Maybe node run options for enable/disable profile.

**Comment by Geod24** [comment]
Here's what I do to get profiling results from the tests:
```bash
for pkg in $(go list ./...); do
echo "++++ $pkg"
PKG_NAME=$(echo $pkg | sed -e 's/\//./g')
go test -cpuprofile cpu.$PKG_NAME.out -memprofile mem.$PKG_NAME.out -mutexprofile mutex.$PKG_NAME.out "$pkg"
done
```

I haven't done it for a running node yet though.

**Comment by anarcher** [comment]
Test run with https://github.com/bosnet/sebak/commit/31676f8c713b1baa79de357f55f19c1c81c571b2

![31676f8c713b1baa79de357f55f19c1c81c571b2](https://user-images.githubusercontent.com/12271/46929023-7c9b3700-d078-11e8-9041-850142cd53ab.gif)

**Comment by anarcher** [comment]
![image](https://user-images.githubusercontent.com/12271/47029174-d8afa980-d1a5-11e8-99e5-1c6b635eae32.png)

70% of syscalls is from `net.Conn`.. It means the node is actually network server not computing.. haha

```
(pprof) top10
Showing nodes accounting for 660ms, 86.84% of 760ms total
Showing top 10 nodes out of 171
      flat  flat%   sum%        cum   cum%
     170ms 22.37% 22.37%      170ms 22.37%  syscall.Syscall
     160ms 21.05% 43.42%      160ms 21.05%  runtime.pthread_cond_signal
     110ms 14.47% 57.89%      110ms 14.47%  runtime.pthread_cond_wait
      60ms  7.89% 65.79%       60ms  7.89%  runtime.memclrNoHeapPointers
      50ms  6.58% 72.37%       50ms  6.58%  runtime.nanotime
      40ms  5.26% 77.63%       40ms  5.26%  runtime.usleep
      20ms  2.63% 80.26%       20ms  2.63%  github.com/agl/ed25519/edwards25519.FeCMove
      20ms  2.63% 82.89%       20ms  2.63%  runtime.netpoll
      20ms  2.63% 85.53%       20ms  2.63%  runtime.stkbucket
      10ms  1.32% 86.84%       50ms  6.58%  boscoin.io/sebak/lib/network.(*ValidatorConnectionManager).connectingValidator
```

**Comment by anarcher** [comment]
![image](https://user-images.githubusercontent.com/12271/47029587-def25580-d1a6-11e8-9444-0977bd5b0d82.png)

I'm not sure but the Ed25519 signature cpu cost is dominant in message handling. :->
