### ISSUE TITLE
Write Integration Test Cases by using Client module

### ISSUE THREAD

**Issue by kfangw** [bosnet/sebak#543]
The client module is newly introduced recently.

By using the module, it is possible to write test cases in golang.

First of all, 
Extend existing test script module to support various scenario
And draw scenarios for the end-user and write the code.

**Comment by Charleslee522** [comment]
@kfangw It is done, right?
If you tagged `fixes #543` or `resolves #543` in #556, then this issue would have been closed automatically :)
