### ISSUE TITLE
List up metrics for node

### ISSUE THREAD

**Issue by anarcher** [bosnet/sebak#548]
For monitoring nodes, we need some application-level metrics such as latest block height, number of tx in tx pool, error count of api requests..

Name | Type | Note
--- | --- | ---
consensus_height | Gauge  | 
consensus_rounds | Gauge | 
consensus_total_txs | Gauge | 
consensus_total_ops | Gauge | 
consensus_validators | Gauge |
consensus_missing_validators | Gauge |
consensus_block_interval_seconds | Summary |
txpool_size | Gauge |
sync_height | Gauge |
sync_errors | Gauge |
sync_duration_seconds | Summary | 
api_request_total | Counter |
api_request_errors_total | Counter |
api_request_duration_seconds | Summary |

**Comment by anarcher** [comment]
Name | Type | Note
--- | --- | ---
consensus_height | Gauge  | 
consensus_rounds | Gauge | 
consensus_num_txs | Gauge | 
consensus_validators | Gauge |
consensus_missing_validators | Gauge |
consensus_block_interval_seconds | Summary |
tx_pool_size | Gauge |
sync_height | Gauge |
sync_errors | Gauge |
sync_duration_seconds | Summary | 
api_request_total | Counter |
api_request_errors_total | Counter |
api_request_duration_seconds | Summary |

**Comment by spikeekips** [comment]
If we can in 6th iteration before v0.1.0, this metrics will be useful to analyze and debugging.

**Comment by zzim2x** [comment]
ToT.! 👍 
It looks good. I'll scrape them.

**Comment by anarcher** [comment]
```
# HELP sebak_api_request_duration_seconds Duration of request.
# TYPE sebak_api_request_duration_seconds summary
sebak_api_request_duration_seconds{method="GET",prefix="/metrics",status="200",quantile="0.5"} 0.000745811
sebak_api_request_duration_seconds{method="GET",prefix="/metrics",status="200",quantile="0.9"} 0.001311313
sebak_api_request_duration_seconds{method="GET",prefix="/metrics",status="200",quantile="0.99"} 0.001311313
sebak_api_request_duration_seconds_sum{method="GET",prefix="/metrics",status="200"} 0.007018600999999999
sebak_api_request_duration_seconds_count{method="GET",prefix="/metrics",status="200"} 9
sebak_api_request_duration_seconds{method="GET",prefix="/node",status="200",quantile="0.5"} 0.000230918
sebak_api_request_duration_seconds{method="GET",prefix="/node",status="200",quantile="0.9"} 0.000230918
sebak_api_request_duration_seconds{method="GET",prefix="/node",status="200",quantile="0.99"} 0.000230918
sebak_api_request_duration_seconds_sum{method="GET",prefix="/node",status="200"} 0.000230918
sebak_api_request_duration_seconds_count{method="GET",prefix="/node",status="200"} 1
sebak_api_request_duration_seconds{method="POST",prefix="/node",status="200",quantile="0.5"} 0.000325723
sebak_api_request_duration_seconds{method="POST",prefix="/node",status="200",quantile="0.9"} 0.000387586
sebak_api_request_duration_seconds{method="POST",prefix="/node",status="200",quantile="0.99"} 0.000487101
sebak_api_request_duration_seconds_sum{method="POST",prefix="/node",status="200"} 0.026616755999999995
sebak_api_request_duration_seconds_count{method="POST",prefix="/node",status="200"} 83
# HELP sebak_api_requests_total Total number of requests.
# TYPE sebak_api_requests_total counter
sebak_api_requests_total{method="GET",prefix="/metrics",status="200"} 9
sebak_api_requests_total{method="GET",prefix="/node",status="200"} 1
sebak_api_requests_total{method="POST",prefix="/node",status="200"} 83
```
