### ISSUE TITLE
Synchronize the time of all nodes

### ISSUE THREAD

**Issue by Charleslee522** [bosnet/sebak#571]
There are two factors of the time in `SEBAK` periodically.
The time is used,
1. to check ballot well-formed.
1. to adjust block time to 5 sec.

**Comment by spikeekips** [comment]
In SEBAK, the time is important for consensus; at this time the exact time is not required, but all the consensus node must keep the almost same time with each other. I propose the way to sync time with other nodes. *A node tries to sync time to well known time server periodically*

**Comment by spikeekips** [comment]
@Charleslee522 I want to listen your opinion~
