### ISSUE TITLE
Too slow to `finishBallot` with lot of operations

### ISSUE THREAD

**Issue by spikeekips** [bosnet/sebak#573]
I am currently testing SEBAK with the stress-testing tool, name is `sebak-hot-body`(https://github.com/spikeekips/sebak-hot-body). I tested with `200` operations in each transaction and `1000` concurrent transactions. The result was terrible, most of transaction was failed to check the confirmation. The logs of sebak is here,
```
DBUG[10-22|12:44:34] payment done node=GCPQ.7DUR ballot=6iX.Vj1
DBUG[10-22|12:44:34] payment done node=GCPQ.7DUR ballot=6iX.Vj1
DBUG[10-22|12:44:34] payment done node=GCPQ.7DUR ballot=6iX.Vj1
...
DBUG[10-22|12:45:32] payment done node=GCPQ.7DUR ballot=6iX.Vj1
DBUG[10-22|12:45:32] payment done node=GCPQ.7DUR ballot=6iX.Vj1
DBUG[10-22|12:45:32] payment done node=GCPQ.7DUR ballot=6iX.Vj1
```
The `ACCEPT`ed ballot went into `finishBallot()` and done well. The only problem was it took so long time to finish, almost **1 minute**.

Considering several timeout of sebak and also timeout of hot-body side, we need to reduce the consumed time to `finishBallot()`.

**Comment by Charleslee522** [comment]
Oh, I really want to see the result after modifying it :)

**Comment by anarcher** [comment]
It's really slow? :->  1000 * 200 is huge operations :-)

**Comment by spikeekips** [comment]
I am writing the patch for using `leveldb.Batch`. This is the latest result with `hot-body`.
```
$ cat /tmp/payment-done.log  | grep 6UBYV1U6BKNCi8x9SwFoMAGNXL8cwpjwKc9EJMt1RSmn  | wc -l
   10000
$ cat /tmp/payment-done.log  | grep 6UBYV1U6BKNCi8x9SwFoMAGNXL8cwpjwKc9EJMt1RSmn  | head -n 1
DBUG[10-23|16:08:25] payment done                             module=noderunner node=GCPQ.7DUR ballot=6UBYV1U6BKNCi8x9SwFoMAGNXL8cwpjwKc9EJMt1RSmn
$ cat /tmp/payment-done.log  | grep 6UBYV1U6BKNCi8x9SwFoMAGNXL8cwpjwKc9EJMt1RSmn  | tail -n 1
DBUG[10-23|16:08:33] payment done                             module=noderunner node=GCPQ.7DUR ballot=6UBYV1U6BKNCi8x9SwFoMAGNXL8cwpjwKc9EJMt1RSmn
```
This tells,
* `10000` payments was completed for the Ballot, `6UBYV1U6BKNCi8x9SwFoMAGNXL8cwpjwKc9EJMt1RSmn`
* For storing the operations, the new patch spent from `DBUG[10-23|16:08:25]` to `DBUG[10-23|16:08:33`, it almost 8 seconds.
