### ISSUE TITLE
client ( mobile wallet ) send request header's content type with `charset=utf-8` automatically.  

### ISSUE THREAD

**Issue by cmcm2222** [bosnet/sebak#590]
As you can see in the attached image, client send to node `payment` request with `charset=utf-8` automatically. Therefore, payment operation can not get response through api handler but `http 404 error status code`.
![contenttype](https://user-images.githubusercontent.com/23111870/47403876-228c2700-d786-11e8-9293-d9bd3bb7940e.png)

**Comment by cmcm2222** [comment]
@kfangw I had talk with ERmind's developer, he couldn't change header's information cause the react native attach `utf-8` automatically. it's issue on react native only.

**Comment by cmcm2222** [comment]
@kfangw so I think 2nd solution looks reasonable.

**Comment by kfangw** [comment]
To help ERmind, 1st option is needed.
I don't want to make it bottle neck.

**Comment by cmcm2222** [comment]
@kfangw  you're right. 
I will take that.

**Comment by cmcm2222** [comment]
@kfangw  I followed your advice, but still same issue.
