### ISSUE TITLE
Skip `Checker` process for incoming ballot is broadcasted by self

### ISSUE THREAD

**Issue by spikeekips** [bosnet/sebak#592]
The current flow for incoming ballot,

1. proposer node makes the ballot after validating the ballot and it's transactions
1. proposer node broadcasts the ballot, **including itself**
1. proposer node receives the broadcasted ballot by itself
1. proposer node validates again

When the number of transactions and it's operations are small, everything is fine, but with big operations and transactions, this double-validating will be huge bottleneck for node.

**Comment by spikeekips** [comment]
@Charleslee522 Please check this issue. :)

**Comment by Geod24** [comment]
@spikeekips : Don't we also have an issue where node A broadcast to B and C, and B and C broadcast back to A ?

**Comment by Charleslee522** [comment]
@Geod24 Yes, Exactly. But it would be filtered.

**Comment by spikeekips** [comment]
@Geod24 Yes, we have, but as we know the infinite broadcasting is filtered by checking TransactionPool :)

**Comment by Geod24** [comment]
@spikeekips : Correct, and we cannot prevent indirections (A => B => C => A). But we could prevent A => B => A which would increase performance.

**Comment by spikeekips** [comment]
@Geod24. Absolutly right.

**Comment by Charleslee522** [comment]
@spikeekips @Geod24 Then we should skip re-validation and re-broadcasting.

**Comment by Charleslee522** [comment]
In this issue, I'll handle double validation only.

**Comment by spikeekips** [comment]
@Charleslee522 I want to share with you about preventing re-validation :)

**Comment by Charleslee522** [comment]
This is resolved in #632
