### ISSUE TITLE
New faster serialization system for performance; replacing `json`

### ISSUE THREAD

**Issue by spikeekips** [bosnet/sebak#606]
There are tons of benchmark result, `json` is slower than XXX. Recently I am digging into #573 and `json` serializing hinders the validation messages(tx, ballot) and storage jobs, especially `LevelDBBackend.Get()`.

Several benchmark results listed the high ranked,
- [ ] aviro
- [ ] messagepack
- [ ] protobuf

If you have another one, please recommend it.

> I want to resolve this issue within this iteration, if possible.

**Comment by spikeekips** [comment]
I want to listen you guys, @zzim2x @outsideris .

**Comment by Geod24** [comment]
There's already https://github.com/bosnet/sebak/issues/434

**Comment by spikeekips** [comment]
@Geod24 Thanks.
