### ISSUE TITLE
Transaction Fee should be collected to 'Common Budget Account'

### ISSUE THREAD

**Issue by spikeekips** [bosnet/sebak#63]
In SEBAK, there are 2 special accounts,
- genesis account(most of blockchains does)
- common budget account

'Common budget account' of our BOScoin is unique feature, it's balance can be used for entire BOScoin network and our community, it's like [common goods](https://en.wikipedia.org/wiki/Common_good_(economics)).

When transaction is finished, it's fee will be collected to 'Common budget' account.

**Comment by Geod24** [comment]
What is the genesis account used for ? Could we somehow use it as the common budget account ?

**Comment by spikeekips** [comment]
@Geod24 The concept of 'common budget account' of BOScoin is concrete, as I said in description and our whitepaper. The current tokennet(stellar) needs to create new account, 'common budget account' because genesis (block) account is widely opened.

Genesis account is for genesis block, and common budget will be for strategic purpose and transaction fee.

There are another issue we should concern, that is, we should migrate blocks from the current tokennet(stellar) including genesis account(it is widely open), so we need to create common budget account at the boot time and the transaction fee should be collected into it.

**Comment by kfangw** [comment]
Somebody should take over this Issue

**Comment by spikeekips** [comment]
@kfangw I will.

**Comment by spikeekips** [comment]
The basic step is almost same with https://github.com/bosnet/sebak/issues/308#issuecomment-423050648 .

If we will distribute tx fee in every block,

1. Proposer injects the new operation, `OperationCollectTransactionFee` into proposer's special `Transaction`(this also will be used for inflation in every block)
1. In `OperationCollectTransactionFee` has fields: 
  - `Amount`: `Amount` is the total transaction fee in the `Ballot`
  - `Target`: `Target` is the public address of common budget account
3. The other validators will verify,
  - `Ballot` has one  transaction of proposer
  - This `Transaction` is signed by Proposer
  - This `Transaction` has valid operations, including `OperationCollectTransactionFee`
  - `Amount` of `OperationCollectTransactionFee ` is correct
4. proposed `Ballot` is accepted
5. `Amount` will be applied to common budget account

---
There are additional issues. 

#### How to broadcast the proposer's transaction
2 of kind solution we can think.
* Broadcast it like normal transactions
* Insert it into `Ballot`

#### Transaction Fee for `OperationCollectTransactionFee`
It should be `0`
