### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by geunwooLIM** [bosnet/sebak#649]
How can I install the sebak?

I follow the installation section in Wiki, but error occur.

Let's say my workstation directory is "/home/boscoin".

I install the sebak in that directory using git clone and now I get the directory "/home/boscoin/sebak"

and I also set PATH of go lang as "export GOPATH=/home/boscoin/sebak"

and then I install it but error occur as bellow
cannot find package "some directory" in any of
/home/boscoin/sebak/src/github.com/~something else

I think this error occur because there is no directory name "sebak/src" but I followed up all guideline but I cannot install it. How can I solve it?

**Comment by Geod24** [comment]
Could you tell us what your `go version` is ?

**Comment by geunwooLIM** [comment]
I downloaded go1.11.2.linux-amd64.tar.gz and install it but when I type in command line "go version", the result is "go version go1.6.2 linux/amd64"

**Comment by Geod24** [comment]
Then you most likely have another version (1.6.2) installed which is used to build sebak instead of the one you downloaded (1.11). You can try to use the path of the binary directly instead.

**Comment by pavulon18** [comment]
I am having the exact same issue as @geunwooLIM .

My go version is:
go version go1.7.4 linux/arm

My machine is a Raspberry Pi running Raspbian OS.

**Comment by Geod24** [comment]
@pavulon18 : Sebak require Go v1.11+
Also, be aware that we haven't tested it on ARM yet, although the code should be portable, I expect you to run out of memory fairly soon.

**Comment by pavulon18** [comment]
@Geod24 
Ga...  I didn't notice the version difference.  My bad.

**Comment by Geod24** [comment]
Let us know if it solves the issue for you. Also we'd be glad to hear if it works on ARM ! (although, if you encounter any issue, please open a separate issue)

**Comment by Geod24** [comment]
@geunwooLIM : Reading the description again, this `GOPATH` setup is wrong. Try to unset it.

**Comment by Geod24** [comment]
@geunwooLIM / @pavulon18 : Any update from your side ?
Without any answer I will close this issue on the 21st.
