### ISSUE TITLE
`IsWellFormed(networkID)` to `IsWellFormed(config.Config)`

### ISSUE THREAD

**Issue by spikeekips** [bosnet/sebak#650]
This is derived from #644 . `Operation.IsWellFormed()` will only have `config.Config` as argument, so it will be good that the `Transaction.IsWellFormed()` and `Ballot.IsWellFormed()` also will have same shape, `config.Config` as only argument instead of 'networkID'.

- [x] `config.Config` will have `NetworkID`
- [x] `Transaction.IsWellFormed()` will have `config.Config` as argument
- [x] `Ballot.IsWellFormed()` will have `config.Config` as argument

**Comment by Geod24** [comment]
Done in #683
