### ISSUE TITLE
Performance issue in `TransactionPool` Hashes

### ISSUE THREAD

**Issue by Charleslee522** [bosnet/sebak#662]
Please see https://github.com/bosnet/sebak/blob/d02013da616a6ef19097be03929cb189f55f650e/lib/transaction/pool.go#L84

I guess, the `transaction.Pool.hashes` field type is string slice not `map[string]bool` because the order is important.
I think it's okay now, because there are less or equal than 1000 transactions in one block,
but later we should be careful.

**Comment by spikeekips** [comment]
@Charleslee522 Yes, I also it will be performance burden. To solve this issue at this time, we can use some ordered map like https://godoc.org/github.com/stojg/golib/sortedmap .

**Comment by Charleslee522** [comment]
> Do you have any performance evidence of `[]string` ?

@anarcherThis is helpful for you.
But as I said, I think it's not that big issue now. I'm just worried about near future.

**Comment by spikeekips** [comment]
Anyway, the searching and update slice is big issue for here.

**Comment by anarcher** [comment]
I guessed that oldest hashed are removed as older order(lt means that 0..10 / 100 ) but this could be bad performace.  l told that with @Charlesllee522 and we have another approach for it :-)
