### ISSUE TITLE
Performance burden in `BallotTransactionsAllValid`

### ISSUE THREAD

**Issue by Charleslee522** [bosnet/sebak#663]
https://github.com/bosnet/sebak/blob/d02013da616a6ef19097be03929cb189f55f650e/lib/node/runner/checker_ballot_transaction.go#L181

Even though there are too many `InvalidTransactions`, we don't have to find all invalid transactions.
When only one invalid transaction is found, we can stop.

**Comment by spikeekips** [comment]
@Charleslee522 Did you check 

https://github.com/bosnet/sebak/blob/5d7e1d08317e2703006cb060f2a1156b43706df7/lib/node/runner/node_runner.go#L558

If `CheckTransactionsOnly` is `false`, we already stop validation and `CheckTransactionsOnly` is `true` in `proposeNewBallot()`

**Comment by Charleslee522** [comment]
@spikeekips Oh, I'll check it. Thanks :)
