### ISSUE TITLE
Checking all address and balance

### ISSUE THREAD

**Issue by Charleslee522** [bosnet/sebak#674]
I think we should testing and monitoring that total balance is consistent across many transactions.
For example, we can make new test like this.
1. Run sebak
1. Send many transactions
1. After n height, total balance is genesis + inflation.

This is a really important in managing the Mainnet.

So we need API or something for getting all public addresses.

**Comment by Geod24** [comment]
Would it be better to have an external tool to do that kind of checks / report ?

**Comment by spikeekips** [comment]
@Charleslee522 This issue also can be listed in #675

**Comment by Charleslee522** [comment]
> Would it be better to have an external tool to do that kind of checks / report ?

@Geod24 That's better. But can we know all addresses from sebak by existing API?
