### ISSUE TITLE
Txs or operations are not indexed when someone received a tx.

### ISSUE THREAD

**Issue by zzim2x** [bosnet/sebak#680]
Payable operations such as payment, create-account, inflation, collect-tx-fee, etc should be indexed.

Any payable operations should exist on a list of operations of the target account.
Any transactions having payable operations should exist on a list of transactions of target account.

**Comment by Charleslee522** [comment]
Does anyone follow this issue?

**Comment by Charleslee522** [comment]
#4 can be resolved together.

**Comment by kfangw** [comment]
depends on #765 #766

**Comment by spikeekips** [comment]
This issue was resolved, right?

**Comment by kfangw** [comment]
solved by #763
