### ISSUE TITLE
Apply no-fee to a transaction related to frozen account.

### ISSUE THREAD

**Issue by soonkuk** [bosnet/sebak#682]
Apply no-fee to a transaction related to frozen account.
It affects freezing, unfreezing request and unfreezing payment.

**Comment by Charleslee522** [comment]
I think it's urgent.

**Comment by soonkuk** [comment]
Each operation type has `HasFee()` method to decide the payment of fee and it can be decided permanently.
But `create-account` and `payment` is different.
It's payment of fee is changed according to operation's target or transaction's source.
If those operations is related to frozen account, there is no fee.
But those operations is not related to frozen account, there is a fee.

So I suggest to make another operations, i.e. freezing operation and unfreezing operation (unfreezing request operation already exits). Then we can make `create-account` and `payment` to pay a fee and `freezing` and `unfreezing` to be excluded from payment of fee.
I think this is clear solution about no-fee policy to certain operation.
What do you think about this?
