### ISSUE TITLE
TransactionsRoot of Block Header does not contains ProposerTransaction

### ISSUE THREAD

**Issue by kfangw** [bosnet/sebak#703]
https://github.com/bosnet/sebak/blob/ed5458f6df19bd92697b3d5357a48d3035591bd3/lib/block/block.go#L46-L60

Is it intended?

@spikeekips

**Comment by spikeekips** [comment]
@kfangw Oops, it's important bug. Please patch it.

**Comment by kfangw** [comment]
solved by #712
