### ISSUE TITLE
'GetTransactionsByAccount` will be needed

### ISSUE THREAD

**Issue by spikeekips** [bosnet/sebak#73]
Currently to get all the transactions of it's source address is implemented, but to get the all the transactions related to the specific account, is not supported. #6 will need this feature.

**Comment by anarcher** [comment]
IMHO, If we have both of `GetBlockTransactionsBySource` and `GetBlockTransactionsByTarget`, we can use it to get all transactions related to  the specific account. What do you think about it?

**Comment by spikeekips** [comment]
@anarcher : IMHO, If we have both of `GetBlockTransactionsBySource` and `GetBlockTransactionsByTarget`, we can use it to get all transactions related to  the specific account. What do you think about it? 

Yes, it will be good. You mean, `GetTransactionsByAccount` will get the transactions, which the given address is source or target both, right? Anyway I missed `GetBlockTransactionsByTarget` :)

**Comment by anarcher** [comment]
I mean that it is possible to fetch all transaction of the specific account using both `GetBlockTransactionsBySource` and `GetBlockTransactionsByTarget` even without `GetBlockTransactionsByAccount`.   :-)  
Anyway `GetBlockTransactionsByAccount` can be convenient for using. But this function should handle two (source, target) iterators as one iterator. IMHO, It can be tricky. But if it is needed, I will make it. :-)

**Comment by spikeekips** [comment]
@anarcher I think `GetBlockTransactionByAccount` will be useful for watching all the transactions that are related to a given account. (https://www.stellar.org/developers/horizon/reference/endpoints/transactions-for-account.html)

> @anarcher : Anyway `GetBlockTransactionsByAccount` can be convenient for using. But this function should handle two (source, target) iterators as one iterator. IMHO, It can be tricky. But if it is needed, I will make it. :-) 

Instead of using `BySource` and `ByTarget` at the same time, how about implement new model that has,
* key: 'bt-byaccount-`BlockTransaction.Source` or `BlockTransaction.Target`-<uuid>`
* value: `BlockTransaction.Hash`

**Comment by anarcher** [comment]
I will make it using this model :-) My concern for this model is that it could be duplication saving  but  it is a kind of index,it makes sense. Thanks :-)
