### ISSUE TITLE
Amount.EncodeRLP is wrong.

### ISSUE THREAD

**Issue by zzim2x** [bosnet/sebak#733]
#730 

I am on my way home. Zzz.

Currently, Amount(10000) is encoded as 0x3130303030.
It should be encoded as 0x853130303030.

0x85 indicates a 5-byte string.

**Comment by kfangw** [comment]
How did you tested it?

**Comment by kfangw** [comment]
a.String() returns 0x3130303030. It is normal.
But when rlp encode byte array should be 0x853130303030

**Comment by zzim2x** [comment]
rlp.Encode(w, a.String())

**Comment by kfangw** [comment]
Lets figure out the reason tomorrow.

**Comment by anarcher** [comment]
Close it :->
