### ISSUE TITLE
`sebakstorage.LevelDBBackend.GetRaw()` should return the 'ErrorStorageRecordDoesNotExist' error

### ISSUE THREAD

**Issue by spikeekips** [bosnet/sebak#74]
Currently `sebakstorage.LevelDBBackend.GetRaw()` returns the simple error when record does not exist, but to distinguish the error clearly, we need to define new error, `sebakerror.ErrorStorageRecordDoesNotExist`. if `GetRaw()` returns `leveldb.ErrNotFound` or `Has()` returns false, `sebakerror.ErrorStorageRecordDoesNotExist` will return.

**Comment by anarcher** [comment]
@spikeekips @zzim2x Plz review it again~

**Comment by anarcher** [comment]
I will close it.
