### ISSUE TITLE
Limit total number of operations

### ISSUE THREAD

**Issue by spikeekips** [bosnet/sebak#747]
Currently we limit the number of transactions and the number of operations in each transaction. With this limit, we can not control and limit the total operations of each ballot. The number of operations affects the elapsed time to validate and save the ballot, so we should limit the total number of operations.

**Comment by Geod24** [comment]
@spikeekips : I am not sure I understand why we want to limit the number of operations ?

**Comment by spikeekips** [comment]
@Geod24 The saving performance is affected by the number of operations in ballot, we already have tx limit and ops limit of one tx, but it does not control the number of operations in ballot.

**Comment by Geod24** [comment]
I thought that was solved by the asynchronous saving of BlockTransactions ?

**Comment by spikeekips** [comment]
@Goed24 Yeah right only in saving time. The ballot validation will be affected.
