### ISSUE TITLE
Transaction History appended as immutable rows

### ISSUE THREAD

**Issue by kfangw** [bosnet/sebak#754]
Current Implementation of Transaction History is mutable.
Because every transaction was decidable when it is submitted,
there can exist state like this `submitted` -> `accepted` or `submitted` -> `rejected`

However, for the special payment operation(refund from the frozen account), the validity of the transaction depends on the state of blockchain(unfreezing operation and block height).
It means that a transaction may become valid even if it was known as invalid.

Hence,
`submitted` -> `rejected` -> `accepted` state transition is needed.

To solve this issue, there can be solutions.

1. A transaction can be submitted when the transaction is not registered in BlockTransaction or Transaction Pool. Transaction History is ignored

2. transaction history is immutable. And just append the state to the database.

3. the transaction history should not be related to business logic.

**Comment by kfangw** [comment]
@spikeekips @anarcher @soonkuk 
What do you think about this?

**Comment by soonkuk** [comment]
I think the operation(like as refund from frozen account is not wrong operation.
It is rejected because that operation did not satisfy the condition(unfreezing operation and block height).
So How about add some status like pending.

submitted -> accepted
submitted -> rejected
submitted -> pending -> accepted

**Comment by kfangw** [comment]
Is pending can exist in BlockChain? @soonkuk

**Comment by soonkuk** [comment]
@kfangw My opinion is to create a different state because the rejected transaction can not be accepted again.

**Comment by kfangw** [comment]
solved by #768
