### ISSUE TITLE
Proposal : Using custom import path “blockchainos.org/sebak”? 

### ISSUE THREAD

**Issue by anarcher** [bosnet/sebak#76]
Go has a mechanism[1] for defining custom import paths by serving HTML meta tags with repository information. Sometimes, Using github import path (github.com/org/repo/...) bothers me. and it doesnt make easy to change repo location too. 
[1]: https://golang.org/cmd/go/#hdr-Remote_import_paths

**Comment by outsideris** [comment]
Set up `https://boscoin.io/sebak/`.
Now it works.
