### ISSUE TITLE
Valid transaction can be denied

### ISSUE THREAD

**Issue by spikeekips** [bosnet/sebak#760]
The rule is simple; valid transaction must be handed over to consensus process. We can think several cases inspite of of this rule. 

The most often case will be,

A. User sent valid tx0
A. It is added into TransactionPool
A. Node died with any kind of reasons and resurrected.
A. After long enough time, user notices tx0 is not stored
A. User send tx0 again
A. But node check the hash of tx0 and found it in block.TransactionPool, not TransactionPool.

**Comment by anarcher** [comment]
When the node is started,  How about that adding txs of the block.TransactionPool to TransactionPool?

**Comment by spikeekips** [comment]
> @anarcher : When the node is started,  How about that adding txs of the block.TransactionPool to TransactionPool? 

I think it makes sense, but I need some fundamental solution for this issue. My scenario is,

* For checking tx is already received or not, node should check,
  - whether tx is in `transaction.Pool`
  - whether tx is in `block.BlockTransaction`
  - not check in `block.TransactionPool`

When node is dead and restarted, the already received, but not yet confirmed transaction can be passed.

**Comment by anarcher** [comment]
> When node is dead and restarted, the already received, but not yet confirmed transaction can be passed.

If TxPool has persistent such as disk saved pending txs, When a node is started, TxPool loads pending txs from disk. It make low performance when TxPool.Add or Remove....  :-\

**Comment by spikeekips** [comment]
> @anarcher : If TxPool has persistent such as disk saved pending txs, When a node is started, TxPool loads pending txs from disk. It make low performance when TxPool.Add or Remove.... :-\

Yes, it makes sense if we have super-speed persistant storage. :)

**Comment by spikeekips** [comment]
#768 will resolve this issue.

**Comment by kfangw** [comment]
@spikeekips do you think that this issue can be closed?

**Comment by spikeekips** [comment]
@kfangw Yes, #768  solves this issue 👍
