### ISSUE TITLE
Seamless migration to sebak from tokennet

### ISSUE THREAD

**Issue by neptunix** [bosnet/sebak#762]
We'd like to get some recommendations on code migration from tokennet to Sebak.

We are currently using node js Stellar SDK to generate transactions and list payments. As far as we can see sebak-testnet is not compatible with Stellar SDK.

What would be the easiest fay for us to migrate to the new network? Do we have to write our own JS library that implements your sebak API or are there any simpler ways?

PS. Please add the `Exchange` label

**Comment by Geod24** [comment]
Ping @spikeekips

**Comment by spikeekips** [comment]
This for remind. This also should be closed.
