### ISSUE TITLE
Sync failure

### ISSUE THREAD

**Issue by Charleslee522** [bosnet/sebak#777]
A node requests sync to height 100~, but sync work done only 2 and 3 height.

[sync-failed.txt](https://github.com/bosnet/sebak/files/2606232/sync-failed.txt)

**Comment by Geod24** [comment]
> Second checking goroutine is checking per 10min.

Do you think we should reduce it ? We aim for a block every 5 seconds, so does it means we might be 120 blocks behind ?

**Comment by anarcher** [comment]
> Do you think we should reduce it ? We aim for a block every 5 seconds, so does it means we might be 120 blocks behind ?

I added a flag (`--sync-check-prevblock`) for it. and the default value of it is 1min.  Almost case should be handled by `Observer` instantly...

**Comment by spikeekips** [comment]
Can we close this?

**Comment by Charleslee522** [comment]
@spikeekips  @anarcher I think we can.
The `sync` in long-term test, has one minute checking term, so 30 sec of default `CheckPrevBlockInterval` is okay.
If the test is failed again, I'll add this term option value as a parameter shorter than now.

**Comment by anarcher** [comment]
I will close it.
