### ISSUE TITLE
'panic: runtime error' occurred

### ISSUE THREAD

**Issue by spikeekips** [bosnet/sebak#792]
4 nodes based on https://github.com/bosnet/sebak/tree/e076904d276c6b5c5d88a1dce6d9f60216e44dfe .

The full logs can be found at https://gist.github.com/spikeekips/37c64a1084307802d8858339563872e5 .
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x60 pc=0x921c12]

goroutine 12210 [running]:
boscoin.io/sebak/lib/consensus.(*RunningRound).RoundVote(...)
	/sebak/lib/consensus/running_round.go:40
boscoin.io/sebak/lib/consensus.(*ISAAC).CanGetVotingResult(0xc00017e000, 0x10ff831, 0x1, 0xc0010e6570, 0x2c, 0xc000c99a40, 0x58, 0xc000c997a0, 0x58, 0xc00016dce0, ...)
	/sebak/lib/consensus/isaac.go:214 +0x182
boscoin.io/sebak/lib/node/runner.BallotCheckResult(0xc41e20, 0xc0010e4b40, 0x0, 0x0, 0x0, 0x0, 0x0)
	/sebak/lib/node/runner/checker.go:375 +0xbe
boscoin.io/sebak/lib/common.RunChecker(0xc41e20, 0xc0010e4b40, 0xbaead8, 0x0, 0x0, 0x0, 0x0, 0x0)
	/sebak/lib/common/checker.go:55 +0x102
boscoin.io/sebak/lib/node/runner.(*NodeRunner).handleBallotMessage(0xc000180000, 0xb5bea0, 0xc001031340, 0xc001031340, 0xc000318e60)
	/sebak/lib/node/runner/node_runner.go:538 +0x52c
boscoin.io/sebak/lib/node/runner.(*NodeRunner).broadcastBallot.func1(0xc000180000, 0xc001030c60)
	/sebak/lib/node/runner/node_runner.go:698 +0x91
created by boscoin.io/sebak/lib/node/runner.(*NodeRunner).broadcastBallot
	/sebak/lib/node/runner/node_runner.go:697 +0xa3
exit status 2
```

**Comment by spikeekips** [comment]
@Charleslee522 I found similar errors as you found.

**Comment by Charleslee522** [comment]
@spikeekips 
It's just my guess. I want to give you small evidence. I think, it's because of data race.
At first, we assumed that a node receives ballots sequentially by channel, so there was no data race in ballot handle process.
But the self ballot is not received through same channel. So the first assume is changed now.

**Comment by spikeekips** [comment]
I found the reason. In the latest log(https://gist.github.com/spikeekips/37c64a1084307802d8858339563872e5#file-sebak-segfault-e076904d276c6b5c5d88a1dce6d9f60216e44dfe-log), the ballot, `HzSooPKEav5hFiSWrpZztapKqc3qwXbMRPCu6rvS1mXs` was checked by checker after same round was finished, so the `RunningRoune` of the ballot was already removed and checker checked the `nil` `RunningRound`.
