### ISSUE TITLE
Block create time is 4 times 4s, then 8s

### ISSUE THREAD

**Issue by Geod24** [bosnet/sebak#802]
Running sebak locally, in the simple configuration (3 nodes), one can see that the time between blocks is cycling:
- 4 blocks are created within 4 seconds of each other (e.g. 12:00:00, 12:00:04, 12:00:08, 12:00:12)
- the last block is created after 8 seconds (12:00:20)

This has two issues:
- The average time seems to be 4 seconds, not 5. Although we should really measure that on a longer scale.
- That behavior means that every 5 blocks, there will be an abnormal delay, which could lead to contentions.

**Comment by Geod24** [comment]
Yes

**Comment by Charleslee522** [comment]
If ‘3 times 4s then 8s’ is correct, not ‘4 times’, then it’s because of the number of validators.
docker/node*.env has four validators but you run only three nodes. So the round that fourth node is validator is expired and takes more time(8sec).

**Comment by Charleslee522** [comment]
@Geod24 ping~ :)

**Comment by Geod24** [comment]
Ah that makes perfect sense. Solved.
