### ISSUE TITLE
BlockOperation save time is lazy than triggering the observer

### ISSUE THREAD

**Issue by kfangw** [bosnet/sebak#824]
From 2a7a05b,
The BlockOperations are saved by goroutine.
Hence, the triggering event is a little bit faster than Saving Time.

It was a reason for the `integration_test_sdk` failed

To fix this at the client side, there is no solution except just waiting with sleep.

How can we solve this?

**Comment by kfangw** [comment]
@spikeekips please consider this when you have enough time.

**Comment by spikeekips** [comment]
@kfangw I guess you agree with me, `time.Sleep` is not real solution for this problem. We should wait for `SavingBlockOperations` finishing it's job. I think we need two logic for this,

* checking operation is saved
* checking timeout.

**Comment by spikeekips** [comment]
Can we close this issue?

**Comment by kfangw** [comment]
It is not resolved.
@spikeekips

**Comment by kfangw** [comment]
I think that we don't need to support `operation` subscribing feature.
If someone want to subscribe operation than subscribe transaction is enough for him/her.

Hence, I want to remove triggering operation save event.

**Comment by spikeekips** [comment]
@kfangw : Hence, I want to remove triggering operation save event.

Removing subscription can be handled by new issue, right?

**Comment by kfangw** [comment]
solved by #848
