### ISSUE TITLE
Stuck after restarting all the nodes at the same time

### ISSUE THREAD

**Issue by spikeekips** [bosnet/sebak#828]
I restarted all the nodes at the same time and then consensus was stuck in all the nodes. The reason is, some node broadcasted the received ballot or the proposed ballot before the enough validators are connected.

> The logs of all nodes can be found at https://gist.github.com/spikeekips/94c2d02a0f736c36d45cfbed709aa9a2 .

**Comment by Geod24** [comment]
Isn't it a case of https://github.com/bosnet/sebak/issues/622 ?

**Comment by spikeekips** [comment]
> @Geod24 : Isn't it a case of #622 ?

It's not. :)
