### ISSUE TITLE
`SavingBlockOperations.Check()` takes too long at startup

### ISSUE THREAD

**Issue by spikeekips** [bosnet/sebak#847]
The elapsed time for `SavingBlockOperations.Check()` will be growing by growing block height.

**Comment by Geod24** [comment]
How long does it take currently ? (And for how many blocks)

**Comment by Geod24** [comment]
I understand there's a linear grow, I just wanted an estimation of the time it takes (let's say per 1k blocks).

**Comment by spikeekips** [comment]
@Geod24 I didn’t estomate, but I know it will be headache :) We can estimate it.

**Comment by spikeekips** [comment]
In `70000` height, it took almost over 1 minutes.
