### ISSUE TITLE
Consensus stuck after recovering enough validators

### ISSUE THREAD

**Issue by spikeekips** [bosnet/sebak#879]
After some trouble of network between validators, as we expected, the disconnected validators will connect each other. At this moment, the broadcasting of ballot would be failed and the consensus can be stuck because they are waiting for ballots, but the other think they already sent it.

The detailed logs can be found at https://gist.github.com/f5e690612b12229b36827162c2503088 .

**Comment by Charleslee522** [comment]
![image from ios 3](https://user-images.githubusercontent.com/15343839/49983270-10b84a80-ffa5-11e8-9263-916720758f52.jpg)
![image from ios 2](https://user-images.githubusercontent.com/15343839/49983271-144bd180-ffa5-11e8-9077-e5a2968cdb98.jpg)

**Comment by Charleslee522** [comment]
API
url: n0/node/ballot_voting_result
return: (recent height, round)all related ballots

How to use
When booting or reconnecting,
1. Set to `SYNC` state
1. Get ballots from validators by `ballot_voting_result` API
1. Merge them and process these ballots
1. The ballots which I sent must be handled separately and specially.
