### ISSUE TITLE
Broken dump from jsonrpc

### ISSUE THREAD

**Issue by spikeekips** [bosnet/sebak#888]
The `DB.Getiterator` with empty prefix produces all the data, but a node fails with this data sometimes. It causes the dumped data does not from same leveldb snapshot.

**Comment by Geod24** [comment]
> It causes the dumped data does not from same leveldb snapshot.

Does not what ?

**Comment by spikeekips** [comment]
> @Geod24 Does not what?

`DB.GetIterator` acts like listing HTTP API. It does not use **real** iterator and snapshot. In every request, it creates a new snapshot. Simply like this,

1. node has `[0, 1, 2, 3]`
1. request `DB.GetIterator` with the limit, 3
1. jsonrpc returns `[0,1, 2]`
1. storage changes `[0, 1, 3, 4, 5, 2]`
1. request `DB.GetIterator` with the limit, 3 and cursor `2`
1. jsonrpc returns `[]` instead of `[3, 4]`
