### ISSUE TITLE
Running a single node without any validators for starter

### ISSUE THREAD

**Issue by Charleslee522** [bosnet/sebak#91]
I think, running a single node is useful for starter. Because when he or she knows about basic blockchain(block, account, PoW, PoS, etc...) but quorum, he can run node quickly and check how it works.
I figure, this would be helpful for the user to join our project.

**Comment by Geod24** [comment]
Suggestion: If the user just references itself as validator, we accept it.

**Comment by Charleslee522** [comment]
@Geod24 How about empty validator or adding standalone option?

**Comment by Geod24** [comment]
Empty validator would be slightly ambiguous, as it could be a misconfiguration.
Standalone option would work, but means adding yet another option to an already large set, hence the suggestion to use a special `--validators`.

**Comment by anarcher** [comment]
> Empty validator would be slightly ambiguous, as it could be a misconfiguration.
Standalone option would work, but means adding yet another option to an already large set, hence the suggestion to use a special --validators.

I agree it. :-).   The special `--validators` means same as `-- validators=self`?  @Geod24

**Comment by Geod24** [comment]
@anarcher : `self`, `none`, or `http://127.0.0.1...`, whatever you feel like :)
