### ISSUE TITLE
Ensure clean checkout builds in Docker

### ISSUE THREAD

**Issue by Geod24** [bosnet/sebak#97]
@outsideris mentioned [here](https://github.com/bosnet/sebak/pull/82#discussion_r195370109) that `docker build .` on a clean checkout should just work.
The issue was that the slow build time inherent to `dep ensure` were killing any attempt to test with Docker. Any solution to this issue should take this into account.

One of the solution we could consider is to use volumes to mount the `vendor` directory, so that `dep ensure` gets cached (it still takes about 10s on my system to do nothing, but better than 10m as before).

**Comment by outsideris** [comment]
As @anarcher said:

> https://golang.github.io/dep/docs/FAQ.html#why-is-dep-slow
> The unavoidable part is the initial clone. dep relies on a cache of local repositories (stored under $GOPATH/pkg/dep)

So, `dep` clone all git repository of our dependencies in `$GOPATH/pkg/dep/sources`. That is, `dep` download all git history rather than specific versions. We have some large git repository, so it is really slow.

**Comment by Geod24** [comment]
If only there was a sane way to do that, perhaps [built into git](https://git-scm.com/book/en/v2/Git-Tools-Submodules) 🤔

**Comment by outsideris** [comment]
`dep` is idiot.

**Comment by Geod24** [comment]
That was fixed since we don't use dep anymore
