### ISSUE TITLE
Stop flooding /connect and use Keep-Alive instead

### ISSUE THREAD

**Issue by Geod24** [bosnet/sebak#99]
We use HTTP2 and setup [keep-alive](https://github.com/bosnet/sebak/blob/bbed51cdeb85fb40a10d01c771e1a5889cd9bf99/lib/common/http2_client.go#L23-L26) but we keep flooding the `/connect` method every second or so.

The [handling](https://github.com/bosnet/sebak/blob/bbed51cdeb85fb40a10d01c771e1a5889cd9bf99/lib/node_runner.go#L201-L206) of the message is also [not used](https://github.com/bosnet/sebak/blob/bbed51cdeb85fb40a10d01c771e1a5889cd9bf99/lib/common/node.go#L187-L194).

@spikeekips is there any reason this was designed this way ?

**Comment by spikeekips** [comment]
@Geod24 Yeah, log messages is noisy. To check the connection is live, `Keep-Alive` seems not to be good enough, because if connection is dead, it will not be caught until idle timeout. 

We can change to log only when first failure of connection.

**Comment by Geod24** [comment]
> it will not be caught until idle timeout.

We can set a low timeout, to match the current behavior.

**Comment by spikeekips** [comment]
> @Geod24 : We can set a low timeout, to match the current behavior.

Yes, it makes sense.

**Comment by spikeekips** [comment]
@Geod24 I have question, if node is down, can the other nodes know that? If not, the broadcasting may be matter.

**Comment by Geod24** [comment]
Fixed in #211
